### ISSUE TITLE
[iPadOS] Back button is missing in Privacy Protection Practices

### ISSUE THREAD

**Issue by tsekityam** [duckduckgo/iOS#1023]
## What did I do
1. Go to https://apple.com
2. Check SSL information of the page

## What did I see
Back button in the top left corner is missing, however, clicking that area will be sent back to the previous page.
![Simulator Screen Shot - iPad mini (6th generation) - 2021-12-23 at 23 42 12](https://user-images.githubusercontent.com/3814422/147263058-660096a9-aa79-4038-88b0-777956ae6b13.png)

## What do I expect
There is a back button

## iPad version
Simulator
* Version 13.2 (972.2)
* SimulatorKit 613.1
* CoreSimulator 783.5
![Simulator Screen Shot - iPad mini (6th generation) - 2021-12-23 at 23 47 43](https://user-images.githubusercontent.com/3814422/147263289-dec94005-940d-47b6-a20d-0c3953b44c4a.png)

## App version
6ece6fb5

**Comment by UnfixedSun** [comment]
@tsekityam @roop @dav @ayoy @st3fan Please assign me this. Thanks.

**Comment by samsymons** [comment]
This will be fixed by https://github.com/duckduckgo/iOS/pull/1373 once it's merged
