### ISSUE TITLE
[iPadOS] back button in privacy protection score card view is not working

### ISSUE THREAD

**Issue by tsekityam** [duckduckgo/iOS#1025]
## What did I do
1. Go to https://apple.com
2. Check privacy protection score card
3. Click back button in the score card header
![image](https://user-images.githubusercontent.com/3814422/147268662-d2a18da7-25b3-480d-8a6c-fd371bf867a2.png)

## What did I see
Nothing happens

## What do I expect
I am redirected to the previous page

## iPad version
Simulator
* Version 13.2 (972.2)
* SimulatorKit 613.1
* CoreSimulator 783.5
![Simulator Screen Shot - iPad mini (6th generation) - 2021-12-23 at 23 47 43](https://user-images.githubusercontent.com/3814422/147263289-dec94005-940d-47b6-a20d-0c3953b44c4a.png)

## App version
6ece6fb5

**Comment by samsymons** [comment]
PR merged 🙂
