### ISSUE TITLE
Reader View - Feature Request

### ISSUE THREAD

**Issue by arawin1979** [duckduckgo/iOS#1031]
Would like to have similar to Safari browsers, having the reader view will be more useful so that DDG can be used as the default browser.

**Comment by samsymons** [comment]
Hey @arawin1979! Thanks for opening this issue, I've tracked your request internally so I'll close this issue for now. This is high on our list of feature requests – I'm not sure when it'll ship, but I'll let you know here when it does.

Thanks again!
