### ISSUE TITLE
Device Fingerprinting Failing

### ISSUE THREAD

**Issue by JohnnyDoe1984** [duckduckgo/iOS#1034]
The iOS browser fails to protect against device fingerprinting: https://coveryourtracks.eff.org/

Are there any steps we can take to protect ourselves against fingerprinting? Also, is there anything I can do as a user to help resolve this issue?

**Comment by Bunn** [comment]
Thanks for getting in touch. We're tracking this [internally](https://app.asana.com/0/414709148257752/1201714568644950/f) 

Once we have an update we'll post on this issue.
Thanks again.

**Comment by brindy** [comment]
Thanks for your interest in DuckDuckGo!  Improving fingerprinting protection is an ongoing process and we'll be rolling out some improvements soon.

We're tracking this internally at https://app.asana.com/0/1163321984198618/1201712959561013
