### ISSUE TITLE
outside collaborator: facing Concurrency is only available in iOS 15.0.0 or newer issue after cloning 

### ISSUE THREAD

**Issue by NaaeemMalik** [duckduckgo/iOS#1051]
Hi guys
I was trying to clone and compile it as per documentation but it says 

`Concurrency is only available in iOS 15.0.0 or newer`

I have done the steps required in docs

**Comment by samsymons** [comment]
Hey @NaaeemMalik! This is likely related to your Xcode version, you need to be on [Xcode 13.2 or later](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes) to compile code which uses Swift Concurrency on versions older than iOS 15.

Are you able to check that you're using Xcode 13.2, and if not, update and try again? Let me know if you're still having issues after that. 🙂 Thanks!

**Comment by NaaeemMalik** [comment]
Thankyou sooo much for this instant help, I updated the xcode and it fixed the issues
