### ISSUE TITLE
Settings menu for ‘automatically clear data’ selections are deselected after closing the menu

### ISSUE THREAD

**Issue by quackquackt** [duckduckgo/iOS#1054]
https://user-images.githubusercontent.com/99611397/153768125-d83583ae-6783-448a-90af-7f09a598ede7.MOV

**Comment by samsymons** [comment]
Thanks @quackquackt, good catch! This bug specifically occurs when you swipe the settings screen down to close it instead of using the back button.

I've opened a pull request to fix this: #1055.
