### ISSUE TITLE
Feature request: Support Data Urls

### ISSUE THREAD

**Issue by HaraldKi** [duckduckgo/iOS#1073]
It looks as if Duckduckgo does not support data urls: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

This in particular prevents "downloading" (i.e. saving locally) images that are generated and/or manipulated on a web page, i.e. for which there exists no blob on a server to fetch.

- Duckduckgo version: 7.65.9.0
- iPad 9th generation
- iOS version 15.3.1
- To reproduce, create a data url for an image and try to load it, see example code below.
- Expected: such an image should be "downloaded", i.e. it should be possible to save it on the iPad (compare to Safari, which does that)
- Actual: Duckduckgo reloads the page and shows as the url: `data:image/png;base64,garblediarbg..`, i.e. the data URL in text form.

Embed the following into an html page and note how other browsers will show a little image after clicking the a-href, while Duckduckgo on iOS does not.

```
<a href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAABmJLR0QA/wD/AP+gvaeTAAAACXBI
    WXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5gIZDRwogAJ/vgAAACNpVFh0Q29tbWVudAAAAAAASGFy
    YWxkJ3MgRWlua2F1ZnNsaXN0ZQreSoiMAAABPklEQVQY0zXBzyuDcRgA8Od533c/bMVk4yBzcxBn
    UkROlJv8B5ITfwF3kaJWDuZApJaDSFkWbtrUTDQbmc025t322t53e9/v++Nx8vkgEYFRh0oMOid0
    i9k4OwBAOWpKceAdQiR9MKAX52PrAmdnZnNxeE032clTYME/NuwdRKrcq7w7o8kI9FpOlJQcEI30
    zvjc3Y7vMOi19F50JSelTMuIF25UvWFaRoPVmaGaX5fCS0N02T3LZ5Mep6/N2cEhL6mirFURMTi6
    AcxQH4q3H9Xk6fOOwmqK9nuXvSAiVVeswjmGHrdF5fM4sekQWgCIiIb806KS/5Hf98cDoGUOiUhm
    Mv1bDc9dJYNUuiajKXCW1kxthbKRo2wEERE5Hvmlvllq7UfeifrbLnICT4bUNaWTJXC2djVPDi+6
    egDgD64YtoFC5zCdAAAAAElFTkSuQmCC">data png</a>
```

**Comment by samsymons** [comment]
Hey @HaraldKi! Thanks for submitting this, I've filed this as a request with our product team ([DuckDuckGo employee link](https://app.asana.com/0/414709148257752/1202180605805684/f)). I'll follow up with you here once I have some more news to report, the employee task has this issue cross-referenced so I'll close it. 🙂
