### ISSUE TITLE
damages links by url-ecoding = character between parameter name and value

### ISSUE THREAD

**Issue by aloistr** [duckduckgo/iOS#1079]
DuckDuckgo in version 7.65.11.0 IOS makes some websites inoperable.
In some links for some parameters, it replaces the = character which separates parameter name and value by an url-encoded %3D

For example, it turns
&sover=-2  
into
&sover%3D-2

Such links of course no longer work.
It seems that this problem started on February 27 or 28, both on IOS and on iPad OS.

We observed this bug on the website https://www.astro.com/cgi/hk.cgi?&lang=e
You need to enter some birth data to get the feature working.
The issue than appears with the links marked by arrows
<img width="400" alt="Screenshot 2022-03-01 at 08 17 07" src="https://user-images.githubusercontent.com/18054955/156122895-f34fe905-0bf2-4309-9e9d-f1b671bc9be4.png">

**Comment by aloistr** [comment]
The wrong url encodings of the = character seeem to be created by DuckDuck go in links which contain a semicolon separator between parameter=value pairs in URLs.
The ; separator is the default created in perl CGI.
The wrong encodings also happen when an URL parameter contains = signs in the parameter valus, like
para=some=some2
here, the parameter value is some=some2 and the = in it must not be url-encoded into %3D.

**Comment by ayoy** [comment]
Hi @aloistr!

Thanks a lot for the detailed report! This issue should now be fixed as we updated how URLs are handled in the address bar. Please give it a try with our latest release (7.67.1). I'm going to close this now, but feel free to comment or re-open if encoding is still broken for you.

Thanks again!
