### ISSUE TITLE
Add option to move fire button to the overflow menu

### ISSUE THREAD

**Issue by CyanBlob** [duckduckgo/iOS#1088]
I'm not somebody that uses the fire button often, so I'd rather have it be out of the way in the overflow menu. Ideally, we could swap in something like a home button into that space.

Having the fire button in that space by default makes sense since it's an important feature, but having the option to move/replace it would be great.

**Comment by samsymons** [comment]
Thanks @CyanBlob! I've opened an internal ticket to sync with the team on Fire button UX improvements, I'll get back to you. 🙂
