### ISSUE TITLE
Allow using the fire button to only clear data, not tabs

### ISSUE THREAD

**Issue by CyanBlob** [duckduckgo/iOS#1089]
I typically have a few tabs open at all times that serve as reminders. Since the fire button would close them, I end up barely using the fire button. Adding a prompt to clear data only, but not tabs, would be helpful.

Another option is to only clear data for sites that are not currently loaded in a tab, leaving those sites alone completely.

**Comment by samsymons** [comment]
@CyanBlob 👋 Thanks for writing in! I've opened a ticket internally ([DDG employee link](https://app.asana.com/0/414709148257752/1202113785689369/f)) to discuss this and will get back to you.

Is the favorites feature something that you'd find useful enough for this purpose? I use the Fire button regularly, but save favorites for websites that I frequently have open. Of course that's not as seamless as only clearing data, but I found it to be a good compromise.
