### ISSUE TITLE
Search ignores plus ("+") characters

### ISSUE THREAD

**Issue by Kalzau** [duckduckgo/iOS#1110]
App version: 7.66.1.0
Device model: Iphone 7
iOS version: 15.3.1

Steps to reproduce the bug:
E.g. search for "c++"
Expected behavior:
Get results for c++

Actual behavior:
"c++" gets replaced by "c  ", returning 
different results.

-------------------------------------
Searching for plus characters exclusively lands the user at the ddg search website with the message "Oops, no search. Please try again." since everything is replaced by spaces. 
The minus character is not affected. Escaping with backslash or surrounding with quotes has no effect.

**Comment by samsymons** [comment]
@Kalzau Thanks so much for this excellent bug report. I've tested this locally and confirmed the issue.

This has been written up [internally](https://app.asana.com/0/414709148257752/1202106061320485/f), I'll flag this with the team and let you know here once this has gone into a release.

Thanks again!
