### ISSUE TITLE
Access previous and forward tabs [Feature Request]

### ISSUE THREAD

**Issue by raphaelzin** [duckduckgo/iOS#1111]
Some sites prevent going back to the previous page, accessing the list of previous pages allows the user to navigate out of that issue.

Safari and Chrome have a long press gesture on the forward and back buttons displaying a table view with such list. DDG could have a modal similar to the `browsingMenu` when long pressing the navigation arrows.

From `MainViewController` The list can be populated by `currentTab?.webView.backForwardList` either `.backList` or `.forwardList`.

I believe this would improve a lot the user experience in some cases.

**Comment by samsymons** [comment]
Hey @raphaelzin!

Thanks for writing in. 🙂 We've got this on our roadmap, and I've added a link to your request to the task tracking this internally. I'll circle back with you here once this makes it into a shipping release, though no promises when that will be.

Thanks!

([Asana reference for DuckDuckGo team members](https://app.asana.com/0/715106103902962/1199195754063824))
