### ISSUE TITLE
Accessibility Issue: "voice search" has the same label as "clear text"

### ISSUE THREAD

**Issue by cb0806151** [duckduckgo/iOS#1124]
I was helping a blind friend of mine use duckduckgo on iOS for searching today and noticed that the "clear text" and "voice search" icon both have the same label (that of "clear text") and it can be quite a bit confusing.

"voice search" icon label
https://github.com/duckduckgo/iOS/blob/3a368431856f16b9f4a192bcc4e2d3c4056730e6/DuckDuckGo/Base.lproj/OmniBar.xib#L198

"clear text" icon label
https://github.com/duckduckgo/iOS/blob/3a368431856f16b9f4a192bcc4e2d3c4056730e6/DuckDuckGo/Base.lproj/OmniBar.xib#L209

**Comment by samsymons** [comment]
Thanks @cb0806151! I've opened a PR to fix this: https://github.com/duckduckgo/iOS/pull/1125
