### ISSUE TITLE
Can't find variable: webkit

### ISSUE THREAD

**Issue by charkour** [duckduckgo/iOS#1222]
Hi, thank you for this great app.

However, when I try to checkout with PayPal on some sites, PayPal will open a new tab. When I complete the PayPal information and return to the ecommerce site, I get an error "Can't find variable: webkit".

I'm an engineer working on an ecommerce site and would love to know how to fix this error. 

Thanks.

**Comment by samsymons** [comment]
Hey @charkour! Thanks for your patience while we got back to you here.

This is a pretty interesting one – do you have a concrete set of steps I can use to test this out? (As an aside, I got an internal bug report about PayPal checking causing a crash in the app today... likely not related, but there's enough going on here now that I'd like to dig deeper)

**Comment by charkour** [comment]
Hi, @samsymons. Thank you for getting back to me. I'll give some more context to help out!

Looking at our logs for the production ecommerce site, we have had 54 instances of `ReferenceError: Can't find variable: webkit` that are from two user sessions. This happens on iOS 15.5 and 14.8 when using the iOS DuckDuckGo browser. These errors seem to most commonly happen when PayPal elements are loaded on the screen and after a payment has been approved, so perhaps I should open an issue on their repos.

<details>
<summary>User-Agents</summary>

`Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 DuckDuckGo/7 Safari/605.1.15`

`Mozilla/5.0 (iPhone; CPU iPhone OS 14_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.8 Mobile/15E148 DuckDuckGo/7 Safari/605.1.15`

</details>


To Reproduce:
- Launch DuckDuckGo iOS
- Go to an ecommerce site that uses PayPal on checkout
- Click the PayPal element to launch a pop up (a pop up on DuckDuckGo iOS will open a new tab)
- Complete the PayPal payment information (tab will automatically close and return to the ecommerce site)
- Client will log the error `ReferenceError: Can't find variable: webkit` when the complete order button is pressed.

We are using the npm packages `@paypal/checkout-server-sdk@1.0.3` and `@paypal/react-paypal-js@7.8.1`. My thought is that the PayPal popup calls an `onClose` callback that tries to reference some window API on the original tab which DuckDuckGo will block.

This issue occurs when using a production or test PayPal environment. Perhaps this is a good [PayPal test environment](https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--default). This is a Storybook deployment linked from the [PayPay React repo](https://github.com/paypal/react-paypal-js). I was unable to verify if the issue occurs here. Is there a way to put the iOS DuckDuckGo app into debug mode in order to see the console logs [similar to iOS Safari](https://www.lifewire.com/activate-the-debug-console-in-safari-445798)?

Would a screen recording of the bug be helpful? Would a test PayPal environment help? Please let me know!

I'm wondering if this is an issue with our site's implementation of PayPal. I was able to reproduce this error just now, both with Privacy Protection disabled and enabled on DuckDuckGo iOS.

Thank you for your time!

**Comment by stewx** [comment]
Anyone figure this out?
