### ISSUE TITLE
Improving BarsAnimator component

### ISSUE THREAD

**Issue by mauriciomaniglia** [duckduckgo/iOS#1236]
Currently the project has a class called `BarsAnimator` that is responsible for the animations to show/hide the navigation bar when the user scroll up or down in the app. The app is working correctly but today there's no automated test to guarantee the correct behavior. I did a quick test and changed the behavior of this class to see if there are tests catching this, but apparently all the tests passed even thought the expected behavior was changed. 

I'm proposing adding some unit tests to cover those behaviors and also move this class to a separate file to make the reading more clean, separate the responsibility and improve maintenance in the future.

**Comment by mallexxx** [comment]
Hey @mauriciomaniglia! Thank you for taking the time to contribute to DuckDuckGo!
Could you please add some more details on what problem are you trying to solve and how the proposed change would increase the product value?
Please refer to  [CONTRIBUTING.md](https://github.com/duckduckgo/iOS/blob/develop/CONTRIBUTING.md)  for more details

Thank you!

**Comment by mauriciomaniglia** [comment]
@mallexxx sure!
