### ISSUE TITLE
Clicking Email Protection results in immediate crash of the app on iPadOS 16.

### ISSUE THREAD

**Issue by W6C** [duckduckgo/iOS#1239]
Environment: 
 iPadOS 16 Beta 3
 DuckDuckGo app 7.68.5.0

Bug:
When clicking the email protection button, the app will crash immediately and disappear. Meanwhile, the DuckDuckGo desktop app button works well.
I will appreciate it if it is fixed soon.

**Comment by samsymons** [comment]
Hey @W6C! Thanks for reporting this. We have a PR open that will be merged this week that resolves it: https://github.com/duckduckgo/iOS/pull/1235

I'll update that PR to link back to this issue so that you get notified when it's merged.

**Comment by W6C** [comment]
> Hey @W6C! Thanks for reporting this. We have a PR open that will be merged this week that resolves it: #1235
> 
> I'll update that PR to link back to this issue so that you get notified when it's merged.

Thanks for your immediate feedback,it’s so nice of you to do it!
