### ISSUE TITLE
JavaScript custom alert view Design Review

### ISSUE THREAD

**Issue by mallexxx** [duckduckgo/iOS#1243]
Original designs
<img width="958" alt="Screenshot 2022-07-20 at 12 32 50" src="https://user-images.githubusercontent.com/365498/179897534-a4b78b2b-5f00-44d3-845a-51041a466cd3.png">

Implementation
<img width="421" alt="Screenshot 2022-07-20 at 12 34 07" src="https://user-images.githubusercontent.com/365498/179897925-149a2bcf-54e2-428b-9835-7595c98231dc.png">
<img width="418" alt="Screenshot 2022-07-20 at 12 34 32" src="https://user-images.githubusercontent.com/365498/179897935-bc10d118-d60f-4280-b35e-6199da78f15b.png">
<img width="897" alt="Screenshot 2022-07-20 at 12 35 07" src="https://user-images.githubusercontent.com/365498/179897939-381f4994-7c0e-442c-817e-89aeb7b6043e.png">
<img width="423" alt="Screenshot 2022-07-20 at 12 35 29" src="https://user-images.githubusercontent.com/365498/179897851-3a0281b9-1719-4ece-9bc6-f8a9ff31473e.png">
<img width="601" alt="Screenshot 2022-07-20 at 12 40 55" src="https://user-images.githubusercontent.com/365498/179898412-2343eec7-9197-4e41-a3c3-93778d88804a.png">

https://user-images.githubusercontent.com/365498/179898089-58c71039-70e0-4459-9f5f-29bb5a2b2e0e.mp4

URL for testing: 
https://www.w3schools.com/jsref/met_win_alert.asp
use "prompt" or "confirm" functions instead of "alert" for testing different kinds of alert

PR: https://github.com/duckduckgo/iOS/pull/1242

**Comment by Bunn** [comment]
Design Review: https://app.asana.com/0/1129367408583813/1202636847279854/f

**Comment by mallexxx** [comment]
Closing this due to Design Review completed
