### ISSUE TITLE
JavaScript custom Alerts localisation

### ISSUE THREAD

**Issue by mallexxx** [duckduckgo/iOS#1245]
Design ref:
![](https://user-images.githubusercontent.com/365498/179897534-a4b78b2b-5f00-44d3-845a-51041a466cd3.png)

Added 2 copy items needing localisation:
"Close This Tab" (comment: "“Close this tab” button for JavaScript alerts", id: "webJSAlert.close.tab.button")
"A message from %@:" (comment: "Alert title explaining the mssage is shown by a website" e.g. "A message from duckduckgo.com", id: "webJSAlert.website-message.format")

**Comment by samsymons** [comment]
@mallexxx @Bunn Closing this down as we no longer need to track it in GitHub vs Asana, but please reopen if you feel otherwise.
