### ISSUE TITLE
no support ios13

### ISSUE THREAD

**Issue by PawNzZi** [duckduckgo/iOS#1255]
my iphone is ios13,but ddg no support ios13,ddk can support ?

**Comment by samsymons** [comment]
Hey @PawNzZi, thanks for writing in!

Unfortunately, we can no longer support iOS 13 as we rely on iOS features that are only available on iOS 14 and above. You should be fine to continue to use the latest iOS 13-compatible release, but I recommend upgrading to iOS 14 if you're able to, for the most up-to-date privacy protection.

**Comment by PawNzZi** [comment]
Thank you for your reply, I expressed my regret, because my equipment is now jailbreak, and iOS15 cannot be jailbroken for the time being, so I can only choose to stay on iOS13.

**Comment by PawNzZi** [comment]
> Hey @PawNzZi, thanks for writing in!
> 
> Unfortunately, we can no longer support iOS 13 as we rely on iOS features that are only available on iOS 14 and above. You should be fine to continue to use the latest iOS 13-compatible release, but I recommend upgrading to iOS 14 if you're able to, for the most up-to-date privacy protection.

Thank you for your reply, I expressed my regret, because my equipment is now jailbreak, and iOS15 cannot be jailbroken for the time being, so I can only choose to stay on iOS13.
