### ISSUE TITLE
Protections Menus

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/iOS#1273]
Will the Protections Menu ever see a dark theme DDG IOS has a nice dark theme but will the Protections Menu get one?

**Comment by samsymons** [comment]
Hey @WillHick! Yes indeed – we do plan on revamping this screen, part of which will be including support for Dark Mode 🙂 

We already use an updated Privacy Dashboard in our macOS browser, which supports Dark Mode as you can see below. You can expect the updated iOS Privacy Dashboard to be similar to this.

<img width="360" alt="Updated Privacy Dashboard" src="https://user-images.githubusercontent.com/183774/184263361-a2c7eaa0-4fd2-4f92-ad35-260417314c0d.png">

**Comment by WillHick** [comment]
Oh awesome, looks amazing and can't wait to see it 👌🏼
