### ISSUE TITLE
Feature Request - New Tab Page

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/iOS#1287]
Can we add some more life to the tab page e.g. Blocking stats, if you add a favourite site it doesn't remove the Dax logo else if looks so empty and bland, maybe some image based wallpapers for it would be awesome to do as some finishing touches?

**Comment by WillHick** [comment]
????

**Comment by samsymons** [comment]
@WillHick Hey Will! Sorry for the delay here.

We have a project related to this exact topic on our roadmap. We use this space in our macOS browser to show various pieces of data like recently blocked trackers, and we'd like to look at revamping the iOS new tab page along the same lines. Wallpaper support is a nice suggestion, thanks. 🙂 

I don't have a timeline on this, but I'll let you know here once there's something to show.

Thanks!
