### ISSUE TITLE
Feature Request: Address Bar at the Bottom of the Screen

### ISSUE THREAD

**Issue by tomeverin** [duckduckgo/iOS#1353]
Migrating from Safari on iOS I have become accustomed to the search/address bar being positioned down the bottom of the screen with the keyboard. It would be great if DDG browser had this as an option too.

**Comment by samsymons** [comment]
Hey @tomeverin! Thanks for suggesting this. This is a popular request, and is something that we're exploring internally.

Since we have this tracked internally, I'll close this issue, but you can expect to hear from me here once I have news to share.

Thanks again!

**Comment by samsymons** [comment]
@tomeverin This feature went live today in version 7.94.0. Let us know if you have any problems with it. Thanks!

**Comment by tomeverin** [comment]
@samsymons works great!
Thanks!
