### ISSUE TITLE
Swap to go back doesn’t work when stage manger is on

### ISSUE THREAD

**Issue by tsekityam** [duckduckgo/iOS#1398]
Asana: https://app.asana.com/0/414709148257752/1203416510097766/f

## what do I have
* iPad Pro (11-inch) (3rd generation)
* iPadOS 16.1.1 (20B101)
* DuckDuckGo 7.70.11.0

## what did I do
1. Turn on stage manager
2. Open DuckDuckGo app
3. Go to Apple.com
4. Click any link in the page
5. Swap from the left edge of the iPad to right.

## what did I see
Other recent app from stage manger is shown on left hand side.

## what did I want
Go back to Apple.com

## notes 
Swap to go back works with safari, but not Firefox, when stage manger is on.

swap from right to left to go forward in DuckDuckGo is working with stage manager.

**Comment by samsymons** [comment]
@tsekityam Thanks for reporting this! I'll check it out and create a task to track this internally.

**Comment by samsymons** [comment]
This was fixed by @fsalata and will be in the December 5th iOS release. Thanks for reporting this @tsekityam!
