### ISSUE TITLE
Feature Request - Add an option to use apple keychain services

### ISSUE THREAD

**Issue by swasey** [duckduckgo/iOS#1502]
About the only thing keeping me from using this browser day-to-day on Darwin is lack of integration with apple's keychain. I assume I'm not alone, hence the feature request.

EDIT: Fix a significant typo

**Comment by samsymons** [comment]
Hey @swasey! Thanks for the request. 🙂 

I'm interested in getting more information about the sort of integration you're looking for – right now, we already offer support for Autofill from iCloud Keychain and third party password managers (see screenshot). Are you referring to the ability to save new credentials to the Keychain?

Thanks!

![IMG_5928](https://user-images.githubusercontent.com/183774/219174567-b1b1e46b-6471-426c-90a8-1d37b13e3b92.PNG)

**Comment by swasey** [comment]
Thanks for the quick response!

I misspoke---I already use (and appreciate) the keychain support on iOS.

I would appreciate similar support on Darwin (e.g., my laptop).
