### ISSUE TITLE
Cloudflare verification loop 

### ISSUE THREAD

**Issue by duckduckgouser** [duckduckgo/iOS#1509]
Hello, 

I am having big time issues with cloudflare keeping access from a bunch of websites. I get stuck in a verification loop. 
Cloudflare is impossible to reach since I am only an end-user and also, ironically I can't acces the website because of this verification window that just keeps on trying to verify the connection is secure. 
It only happens with the Duckduckgo browser. I have tried a different internet connection, tried a VPN, I ran malware detection and I have no viruses, I deleted all the history, nothing helps.
Any ideas? Cheers

**Comment by samsymons** [comment]
@duckduckgouser Thanks for the report! To clarify, you're seeing this on our iOS app correct? I wanted to double check since this is a problem that has largely been affecting our macOS app.

Either way, we're working on this one internally and are aiming to have it fixed soon. I'll let you know here once I've got an update.

Thanks again!

**Comment by duckduckgouser** [comment]
Ah no sorry I see I'm on the wrong page. It is not the app, it is happening on the browser on my macbook

**Comment by samsymons** [comment]
No problem! That's a relief, since we're focusing on the issue in the macOS browser right now, due to not seeing any reports of it on iOS. We have a new macOS build currently on its way to release, I'll let you know when that's available later today.

**Comment by duckduckgouser** [comment]
Thanks for your quick response! Looking forward to it, hopefully it will solve the issue.

**Comment by samsymons** [comment]
I've just released an update to the App Store and non-App Store builds of the macOS browser, version 1.34.3. Let me know if this fixes your issue – I'll keep this issue open until everything's looking good here. Thanks again!

**Comment by duckduckgouser** [comment]
Thanks for the update! - it fixed access to both the cloudflare website as well as the chatGPT website, however I'm still experiencing trouble with the Canva website. Not sure if it helps but I've attached a screen recording of what I'm seeing. 

https://user-images.githubusercontent.com/125898019/220282935-49c944bb-a871-490e-9195-e93329070fb7.mov

**Comment by duckduckgouser** [comment]
Another update, since I just checked, trying to access the canva website now gives me this message: 

"This browser is unsupported, download the desktop client
You are using an old version or a browser that we do not support. To continue using Canva, please download the desktop client." 

I'm guessing since I was also troubleshooting this issue with the Canva team, they made this change on their side?

**Comment by duckduckgouser** [comment]
Last update, it seems to be fixed. I can access the Canva site again, and haven't encountered any other websites with the verification loop issue. 

Thanks for the support!

**Comment by samsymons** [comment]
Great, thanks for confirming! We made some additional changes yesterday, I'm glad to see this has gotten it working for you again. Please reach out if you run into any other problems 🙂
