### ISSUE TITLE
Feature Request - Add to Home Screen

### ISSUE THREAD

**Issue by benfuddled** [duckduckgo/iOS#1570]
iOS 16.4 released today and with it the ability for third party browsers to pin web pages to the Home Screen. It would be great if DDG had this feature!

Via the [webkit.org blog](https://webkit.org/blog/13966/webkit-features-in-safari-16-4/):

> iOS and iPadOS 16.4 also add support so that third-party web browsers can offer “Add to Home Screen” in the Share menu. For the details on how browsers can implement support, as well more information about all the improvements to web apps, read [Web Push for Web Apps on iOS and iPadOS](https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/).

**Comment by samsymons** [comment]
Hey @benfuddled! Thanks for the request – I agree. 🙂 I'm looking into adding support for this and will get back to you once I've got something to report.

**Comment by samsymons** [comment]
We prototyped this today, and it works really nicely. However, because Xcode 14.3 requires macOS 13, we're blocked on releasing this until https://github.com/actions/runner-images/issues/6426 is resolved.

We'll release this change as soon as we're able – sorry about that.

**Comment by samsymons** [comment]
@benfuddled We're now unblocked from shipping this feature, it'll be available when this PR goes into a release: https://github.com/duckduckgo/iOS/pull/1704
