### ISSUE TITLE
<meta content="telephone=no" name="format-detection" />

### ISSUE THREAD

**Issue by betslus1** [duckduckgo/iOS#1577]
not working this metatag in browser for disable detection mobile number
<meta content="telephone=no" name="format-detection" />

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html

**Comment by sudeepa88** [comment]
Would you please explain this ?

**Comment by betslus1** [comment]
All numbers turn into mobile phone numbers and I can't turn it off. The formatting of pages is completely spoiled.

I have div tag, with attribute "editable" with big number. If I open page with DuckDuckGo browser automatically work event "onchange" and number turn in phone number with saving wrong data on server. 

All another browser use meta tag for disable convertation number to phone number.
