### ISSUE TITLE
DuckduckgoTestflight 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [duckduckgo/iOS#1673]
You know what would be easier is if you guys notify us that you updated duckduckgo through TestFlight and allow us to see what were the changes within the app instead of making me wait to update my duckduckgo app through my iPad tablet. Seriously.

**Comment by samsymons** [comment]
Hey @ImpenetrableNoble, thanks for submitting this issue!

We used to maintain a TestFlight channel, but retired it as it didn't have a lot of traffic. We publish new releases every Monday, and as our builds are generated on Fridays we found that that gave the TestFlight channel very little time in which to provide actionable feedback – after all, TestFlight builds have to go through the same app review process as App Store builds, so by the time it's approved by Apple then the new build has usually already been released on the App Store anyway, making the TestFlight build redundant.

Unfortunately App Store builds don't get access to the same release notes UI that Apple provides for TestFlight builds, but I like the core idea behind this suggestion and it's something we'd like to improve upon in the future.

Thanks again, and let us know if you have any other issues or suggestions!
