### ISSUE TITLE
Add Support for Folders on New Tab Page

### ISSUE THREAD

**Issue by dimeeentor** [duckduckgo/iOS#1701]
Currently, the new tab page in the DuckDuckGo app only displays a grid of bookmarked websites. While this is useful for quickly accessing frequently visited sites, it can become cluttered and difficult to manage as the number of sites increases.

Other browsers like Safari allow users to create and organize folders on the new tab page to group related websites together, providing a more organized and streamlined browsing experience.

Therefore, it would be great if the DuckDuckGo iOS app could introduce support for folders on the new tab page. This feature would allow users to group their favorite websites and organize them into categories for easier access.

This would not only enhance the user experience but also increase the app's usability and make it more competitive with other browsers that already offer this feature.

In my case, I'd like to have on the new tab page different folders like: Social/News/AI etc., but right now I have to create a ton of favorite bookmarks or create folders in Bookmarks menu and that actually not convenient for me at all.

Thank you for considering this suggestion.

**Comment by basicuser01** [comment]
I agree this is a critical missing feature. It takes way too many taps to get to bookmarks compared to Safari.

**Comment by brindy** [comment]
Thanks for raising this.  I will share with the product team. Please keep an eye on coming releases for updates in this area.  Thanks.

Tracking this internally at https://app.asana.com/0/715106103902962/1207667062239992/f
