### ISSUE TITLE
Feature Request - Support Multiple Windows

### ISSUE THREAD

**Issue by Hamster45105** [duckduckgo/iOS#1859]
Most other iPadOS browsers already have support for having multiple windows open, so it would be good if DuckDuckGo could have the same.

**Comment by basicuser01** [comment]
I created an account on here just to say this is preventing me from switching to DDG. With Stage Manager and Split View it’s kind of silly to not have this feature, and I don’t know how I can get serious work done without it. I have to keep using Safari and Brave until this is fixed.

**Comment by brindy** [comment]
Hi, sorry for the delay in reply.  We're tracking this internally at https://app.asana.com/0/715106103902962/1207667062239999/f
