### ISSUE TITLE
Localizations / Maintenance update

### ISSUE THREAD

**Issue by Thanaen** [duckduckgo/iOS#19]
Hello,
I think it would be something great to add localizations to the app, I really miss it (French).
Plus, I think there should be a maintenance update, or some features added or ergonomic enhancements, as it is quite "repulsive" to see an app that has been last update in 2016! (I'm not saying that you're trash, hu, just telling that maybe, just maybe, a little maintenance won't hurt the app!

Thanks for reading guys, keep up the good work!

**Comment by subsymbolic** [comment]
Thanks for your feedback. I think you may have intended it for our currently live app at https://github.com/duckduckgo/ios-search-and-stories. The good news is that this repo contains the prototype of a new private browsing app that we're building. We haven't added localization to this one yet but will in the future.
