### ISSUE TITLE
Feature Request - smoother animations

### ISSUE THREAD

**Issue by dimeeentor** [duckduckgo/iOS#1953]
It would be better if you rewrite the animation to open tab viewer, just to compare with Safari or even Orion Browser and DuckDuckGo Browser animations are not so good. Thanks for you attention.

**Comment by jairajput** [comment]
Can You Assign Me This

**Comment by jairajput** [comment]
I would  Like To Work On That

**Comment by dimeeentor** [comment]
How I could assign you? There is no option for me to do it.

**Comment by jairajput** [comment]
Okay
