### ISSUE TITLE
Feature Request - Homepage

### ISSUE THREAD

**Issue by WillHick** [duckduckgo/iOS#1964]
Are there current plans to expand and revamp the current DDG NTP (New Tag Page) and add new features, such as:

- Adding browsing statistics like the desktop browsers
- Removing the black background and changing to a different colour
- Adding the search bar to the middle of the screen like other platforms for a fluent look and experience

Thanks

**Comment by balogun14** [comment]
@WillHick can you explain this a bit more

**Comment by WillHick** [comment]
> @WillHick can you explain this a bit more

The DDG homepage should feature more features such as browsing stats like (blocking stats) and folders for bookmarks etc

**Comment by balogun14** [comment]
@WillHick ohh
