### ISSUE TITLE
Feature Request - Reader mode

### ISSUE THREAD

**Issue by dimeeentor** [duckduckgo/iOS#2022]
Would be great if DuckDuckGo iOS app could have native reader mode like Safari does.

**Comment by AusArnon** [comment]
> Would be great if DuckDuckGo iOS app could have native reader mode like Safari does.

**Comment by balogun14** [comment]
@dimeeentor can you explain this more i will like to work on this

**Comment by dimeeentor** [comment]
@balogun14 based on the fact that DuckDuckGo Browser on iOS does not have proper adblocker on websites, besides English ones, in my case, on Ukrainian ones I usually see some ads, so I have to use other Safari with Ghostery extension or reader mode if the extension won’t block regional ads. 


I would like to see a native reader mode with DuckDuckGo style guidelines and not like Brave/Firefox do, their reader mode is awful.

On the App Store there are only two apps that have really good reader modes: Safari and Orion browser (Orion browser, I suppose is using Mozilla’s readability, but with Apple style guidelines).

So, if DuckDuckGo browser would have proper reader mode with settings pretty same like Safari does or with your own ideas how to make it in DuckDuckGo way, I’m pretty sure that would be awesome browser to use, and I won’t care if I’m looking at the regional website.

![telegram-cloud-photo-size-2-5240450079758864743-y](https://github.com/duckduckgo/iOS/assets/32683179/8847f919-a3e2-452d-b861-39fd14461b2d)

**Comment by balogun14** [comment]
@dimeeentor i would like to work on this but
