### ISSUE TITLE
Bottom Bar Bug – Hiding but keeping blank area after scroll

### ISSUE THREAD

**Issue by xtiandiaz** [duckduckgo/iOS#2159]
App Version: 7.95.0.0
iOS: 15.7.9
iPhone: 6S

https://github.com/duckduckgo/iOS/assets/4345136/0c6c5005-b69a-46f2-9713-bb72ff427cc2

**Comment by dimeeentor** [comment]
App version: 7.96.0.0
iOS: 17.1.1
iPhone 11
Same problem:

<img width="414" alt="image" src="https://github.com/duckduckgo/iOS/assets/32683179/98638ca0-e6e6-4322-8fdc-337d9fe2fc93">

**Comment by vivekismittal** [comment]
Can i pick this issue if it is still there?

**Comment by dimeeentor** [comment]
@vivekismittal Yup, it’s still there.

**Comment by samsymons** [comment]
Hey there! This issue has been addressed here, and will go live in production within 1-2 weeks: https://github.com/duckduckgo/iOS/pull/2330
