### ISSUE TITLE
Universal Links not working

### ISSUE THREAD

**Issue by arcticmonkey** [duckduckgo/iOS#2301]
I am experiencing an issue with Universal Links when using Duck Duck Go for IOS. Universal links are not opening in their native apps, and are instead opening in a new tab.

**App Version**: `7.101.0.1`
**IOS Version**: `16.7.2`
**Model Name**: `iPhone X`
**Other Details:**  `Open Links in Associated Apps: ON`
![IMG_79742](https://github.com/duckduckgo/iOS/assets/89162813/570ea69f-a5f2-4a11-8c2f-eaf22b0ab740)

## Steps to Reproduce
1. Run the following HTML code on a simple web server accessible by your Duck Duck Go IOS instance
   1. If you have NodeJS installed, run `npx http-server <path-to-source-code-directory>`
2. For the full demo, please ensure you have either `Google Maps` or `Waze` installed AND `Apple Maps` installed
3. Open Duck Duck Go and access the webpage
4. Click Google or Waze links.
   1. You will note that the map opens in a new tab
5. Click Apple Maps
   1. You will note that this opens in the Apple Maps app

## Expected Behavior: 
The links should open their corresponding app

## Actual Behaviour: 
The links open a new tab

## Additional information
1. Perform the same steps above in either Google Chrome, Safari or Firefox on your IOS device and all links open in their correct apps.

#### HTML Code for Demo
```html
<!-- filename: index.html -->
<html>

    <head>
        <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    </head>

    <body>

        <a href="https://www.waze.com/ul?ll=44.6533753993004%2C-81.13464470301994&navigate=yes">Waze</a>
        <br>
        <a href="https://www.google.com/maps/dir/?api=1&origin=45.22738091447632%2C-81.62266720155588&destination=44.6533753993004%2C-81.13464470301994&travelmode=driving">Google</a>
        <br>
        <a href="http://maps.apple.com/?t=m&dirflag=d&daddr=44.6533753993004,-81.13464470301994&saddr=45.22738091447632,-81.62266720155588">Apple</a>

    </body>

</html>
```

**Comment by fdbeirao** [comment]
A customer of mine has also opened a ticket in our internal tracking system regarding this issue (for us it was with an App Store link, not opening the AppStore, but instead navigating to the app store).
Curious to see the developments of this issue. Cheers.
