### ISSUE TITLE
Fire button not deleting current website

### ISSUE THREAD

**Issue by mattlikespie** [duckduckgo/iOS#2435]
iOS 17.3 (21D50)
DDG v 7.17.0.0

Intermittent issue: using the Fire button will not erase the current website.

1. Navigate to a website. 
2. Use the Fire button. 
3. URL is still in the address bar.
4. Tap Go button, browser navigates to that page. 

Once this bug is active, user can navigate to any other website and continue this cycle. 

The only way to get the URL out of the address bar is to tap Cancel (top right).

**Comment by mattlikespie** [comment]
This issue has been present since v 7.106.0.

**Comment by andrewkember** [comment]
This is what the retained url (or search text in this case) looks like. 

![image](https://github.com/duckduckgo/iOS/assets/1770102/0b1b4aa8-0160-40dd-9ced-4abf5d0714ce)

**Comment by mattlikespie** [comment]
Yes, the URL, or in this example the search term,  is highlighted.

https://github.com/duckduckgo/iOS/assets/113533724/35e1c32c-9887-4a48-a735-b26e9f490057

**Comment by andrewkember** [comment]
Today's 7.108.0 seems to fix it - what are you seeing, @mattlikespie? Does that fix it for you?

**Comment by mattlikespie** [comment]
It actually hasn't popped up since I installed 7.107.1.1 over the wekend. Will check 7.108.0, but assume it has been fixed. Thanks!

**Comment by mattlikespie** [comment]
Update: this issue has returned in v 7.108.0.4.

**Comment by mattlikespie** [comment]
This issue has popped up again. When using the fire button, the "flame" effect trips, but the url is not removed and can be accessed using the Go button (bottom right). 

DDG v7.132.0.3
iOS 17.6.1 (21G93)
