### ISSUE TITLE
Change Tabs UI Lagging

### ISSUE THREAD

**Issue by davidcruzcs** [duckduckgo/iOS#25]
When using the “Change Tab” button, animations for both presenting and dismissing the view, makes the UI lag. An example of this can be found in the video shown below:

https://youtu.be/d1NQKkZalug

This issue is part of a complete analysis being made to the DuckDuckGo open source iOS App
https://docs.google.com/document/d/1GY7_LbkmIzJgMrLcaoGT1i6OOF3qHF4bHFdi5eF0Els/edit?usp=sharing

**Comment by subsymbolic** [comment]
Thank you for logging this! We have sped up the animation speed in PR https://github.com/duckduckgo/iOS/pull/32.
