### ISSUE TITLE
Can't Build project ?

### ISSUE THREAD

**Issue by chihung93** [duckduckgo/iOS#255]
MacOS : 10.12.6 (16G1212)
XCode : Version 9.2 (9C40b)
Hello guys,
I have an issue when building your project on last Xcode. 
What solution do I need to use to resolve this problem?

Thanks.

Hungs-MacBook-Pro:iOS-develop hungdct$ carthage bootstrap --platform iOS
*** Checking out OHHTTPStubs at "6.0.0"
*** Checking out SwiftyJSON at "4a62eb3a37e1e694a7f83d50093e803f966055ba"
*** Checking out SimulatorStatusMagic at "tags/1.9.5"
*** Checking out Device.swift at "0.5"
*** Checking out Alamofire at "4.5.0"
*** Checking out Kingfisher at "3.10.3"
*** Checking out Toast-Swift at "2.0.0"
*** xcodebuild output can be found in /var/folders/b_/n65p14fn67g8p21mpms9hflm0000gn/T/carthage-xcodebuild.OgtzLx.log
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/hungdct/Downloads/iOS-develop/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

**Comment by brindy** [comment]
Hi - sounds like you have this problem:

https://stackoverflow.com/questions/40743713/command-line-tool-error-xcrun-error-unable-to-find-utility-xcodebuild-n

Also, the README needs to be updated, but we now use a submodule so you need to check out the code as follows:

`git clone --recursive git@github.com:duckduckgo/iOS.git`

And you can run the following to build and execute the unit tests, which will give you confidence everything is good.  This will also do the Carthage bootstrap if needed.

`./run_tests.sh`

**Comment by brindy** [comment]
I'm going to close as not an issue.  Feel free to reach out for help if you need it.
