### ISSUE TITLE
1Password integration?

### ISSUE THREAD

**Issue by jplock** [duckduckgo/iOS#256]
It would be great to support 1Password natively within the app.

**Comment by brindy** [comment]
Thanks for the suggestion. We have improved password management on our backlog so we'll definitely consider it.

**Comment by alaaadnan229** [comment]
https://drive.google.com/open?id=1EXQAT8t3BJP-CKl-hX8jqMJmQZ3kxnRt

**Comment by brindy** [comment]
We're evaluating our roadmap just now so have taken this feedback in to account. Thanks!
