### ISSUE TITLE
Drop SwiftyJSON Dependency

### ISSUE THREAD

**Issue by Marcocanc** [duckduckgo/iOS#257]
SwiftyJSON is only used in 3 places ([1](https://github.com/duckduckgo/iOS/blob/develop/Core/AtbParser.swift), [2](https://github.com/duckduckgo/iOS/blob/develop/Core/TermsOfServiceListParser.swift), [3](https://github.com/duckduckgo/iOS/blob/develop/Core/DisconnectMeTrackersParser.swift)).
Swift 4 offers built in [JSON Decoding](https://developer.apple.com/documentation/swift/encoding_decoding_and_serialization).
Would be nice to have one less dependency.

**Comment by brindy** [comment]
Good point! Thanks for the suggestion.

**Comment by brindy** [comment]
This was done in PR #271 - thanks for your input and contribution. :)
