### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by huangboju** [duckduckgo/iOS#259]
![image](https://user-images.githubusercontent.com/14818224/35421683-82a5317c-027f-11e8-8aeb-6a1831e9ee51.png)

**Comment by robinvvinod** [comment]
Add the `/src` folder from https://github.com/duckduckgo/ios-js-support  to `/submodules/ios-js-support` in your project directory for a quick fix.

This may not be the correct way but it was the only one that worked for me. Hope this helps!

**Comment by timpalade** [comment]
@huangboju run this command `git submodule update --init --recursive
`. It will get all submodules for this project (for now there is only one).

**Comment by brindy** [comment]
Yep, bringing in the submodule is how to fix this.  Thanks @timpalade.

I will get the README updated today.
