### ISSUE TITLE
No Eventual Connectivity

### ISSUE THREAD

**Issue by davidcruzcs** [duckduckgo/iOS#26]
There is no Eventual Connectivity management so the user will know when he or she no longer has access to the internet. In addition, retrieving the internet connection does not continue downloading the pending data. The behavior described above can be observed in the following video:

https://youtu.be/3xmEQBXeXBU

This issue is part of a complete analysis being made to the DuckDuckGo open source iOS App
https://docs.google.com/document/d/1GY7_LbkmIzJgMrLcaoGT1i6OOF3qHF4bHFdi5eF0Els/edit?usp=sharing

**Comment by subsymbolic** [comment]
Thanks @juandavidcruzs, I'll have a look at your PR this week. Thanks for the analysis too, it will be interesting to cross-reference with your results when we do internal profiling before we go live.

A note on your analysis, you make references to our app store listing. This sourcecode is for a prototype which is currently unreleased to the public - it doesn't have an app store listing or ratings. Perhaps you meant to analyze our live app at https://github.com/duckduckgo/ios-search-and-stories?

**Comment by mayassuarez172** [comment]
Good Ideas,  Thanks for the analysis too, it will be interesting to cross-reference with your results when we do internal profiling before we go live for more 
[https://github.com/mayassuarez172](https://github.com/mayassuarez172)
[https://github.com/mayassuarez172/blue-kitchen-cabinets](https://github.com/mayassuarez172/blue-kitchen-cabinets)
[https://mayassuarez172.github.io/blue-kitchen-cabinets](https://mayassuarez172.github.io/blue-kitchen-cabinets)
