### ISSUE TITLE
[Enhancement] Add setting to clear data on termination

### ISSUE THREAD

**Issue by robinvvinod** [duckduckgo/iOS#260]
Hi,

If possible, please add a setting to allow us to clear all data and tabs (similar to the fire button) when we close the app. 

Maybe something like this on the AppDelegate.swift?
```
func applicationWillTerminate(_ application: UIApplication) {
        ServerTrustCache.shared.clear()
        WebCacheManager.clear() {}
        tabManager.removeAll()
}
```

Thank you!

**Comment by brindy** [comment]
Thanks for the suggestion.   We probably won't take this approach as it's not very reliable, but we have already been considering a more configurable alternative that hopefully our users will like.  

We're currently addressing top priority feedback from the launch then will look at things like this.

Thanks again for your interest! :)
