### ISSUE TITLE
Prevent the opening of installed apps

### ISSUE THREAD

**Issue by Jahhein** [duckduckgo/iOS#268]
In any search results, such as Instagram, if you click on the link the corresponding application installed on the phone will open. 

Perhaps this can be fixed so it does not happen, and put into the settings for users to turn on and off.

**Comment by Jahhein** [comment]
This is on iOS to be exact.

**Comment by brindy** [comment]
Hi. Thanks for the suggestion.  

This is WKWebView's default behaviour and currently has no public API for disabling it.  See this SO for more details:

https://stackoverflow.com/questions/38450586/prevent-universal-links-from-opening-in-wkwebview-uiwebview/44942814#44942814

**Comment by Jahhein** [comment]
Ahh. I wasn’t aware of that. Guess that’s something to always watch out for. Thank you.

**Comment by brindy** [comment]
Going to close this as we're discussing what we can do about it internally, but for now there's not much we can do really.
