### ISSUE TITLE
[Bug] Swiping to close tab and quickly clicking new tab causes crash

### ISSUE THREAD

**Issue by ConnorSmith-pf** [duckduckgo/iOS#2757]
DuckDuckGo Version: 7.115.0.4
iOS: 17.4.1 (21E236)
Model: iPhone 11 Pro

When swiping to close a tab and quickly tapping the plus to open a new tab, DuckDuckGo crashes 

https://github.com/duckduckgo/iOS/assets/80120827/23c33829-e50e-4cf7-b13a-d16dc854a020

**Comment by dus7** [comment]
@ConnorSmith-pf thank you for reporting! It'll be fixed in next release.
