### ISSUE TITLE
There’s no iPad keyboard shortcut to close the window

### ISSUE THREAD

**Issue by basicuser01** [duckduckgo/iOS#2783]
Almost all other apps and browsers can close the window using either CMD-W or CMD-Shift-W (usually the former). Neither works with DDG and it is disruptive to keyboard users.

**Comment by brindy** [comment]
Hello, we don't support windows explicitly at this time.  Cmd-W should close your current tab though.  I've just validated that this works.  Please re-open if that's not the case or you can provide more details.  Thanks.
