### ISSUE TITLE
Bookmark Management Solution for iPad/iPhone

### ISSUE THREAD

**Issue by basicuser01** [duckduckgo/iOS#2788]
It is currently a nightmare attempting to move a significant number of bookmarks around. 

I imported bookmarks to DDG yesterday and found that many of the bookmarks were in the wrong file tree. Normally, this is a quick fix: just drag and drop a bunch of bookmarks into the right folder or use a select all command. But this is not currently possible. 

The way it is right now requires the user to click on each individual bookmark or folder… and manually… one… by… one…. switch the bookmark to the right location.

If the Apple API doesn’t allow for drag and drop or select all functions, then some workaround, app, or web app is needed to avoid switching to DDG being a being a big nuisance for prospective users.

**Comment by brindy** [comment]
Hello, please take a look at our desktop apps. You can use the "Sync" feature to connect them and use the desktop app's re-ordering capability.  Hope that helps.  Please re-open if you're still having trouble.  Thanks.
