### ISSUE TITLE
White Theme or maybe different color themes?

### ISSUE THREAD

**Issue by roseusgarcia** [duckduckgo/iOS#280]
Hello all,

I noticed in the app there are no options for customizing the look of the app. Maybe a white theme or a pure black theme for OLED display on the iPhone X. Just a suggestion mostly.

Have a good one!
Rose

**Comment by brindy** [comment]
Hi @roseusgarcia - thanks for the suggestion! :)

**Comment by roseusgarcia** [comment]
@brindy you're very welcome! Hopefully it gets implemented! :)

**Comment by brindy** [comment]
We're currently evaluating our road map and will take this feedback in to consideration.  Thanks again for taking the time to get in touch. :)
