### ISSUE TITLE
”Bookmark All Tabs” crashes when many tabs are open

### ISSUE THREAD

**Issue by thumbty** [duckduckgo/iOS#2806]
I’ve managed to open over 17000 tabs. I’d like to archive those and start clean. I tried using the “Bookmark All Tabs” button, but that freezes and eventually crashes the app.

App version 7.116.0.3
Device model iPhone 15 Pro Max
iOS version 17.4.1

**Comment by brindy** [comment]
Hello, a reddit user was in a similar position (27k tabs) and managed to complete this successfully.  I can imagine it took some time.  Please give it another shot if you can.  Re-open if you're still having problems.  Thanks.

**Comment by thumbty** [comment]
I just tried again twice, and duckduckgo crashed both times while trying to save the tabs to bookmarks. I also tried after a fresh reboot.

**Comment by thumbty** [comment]
I think I might not have permissions to re-open the issue

**Comment by brindy** [comment]
Hi, OK, I have created an issue internally to look at this.  We know there are ways to improve it.  Thanks for your patience.

Internal reference: https://app.asana.com/0/414709148257752/1207676927051572/f

**Comment by Home1730** [comment]
adrian0315024
