### ISSUE TITLE
Implement App Preview Blurring 

### ISSUE THREAD

**Issue by noob-programmer1** [duckduckgo/iOS#3121]
## Description
To enhance privacy and security in the DuckDuckGo iOS app, we need to implement a feature that blurs the app content when it appears in the app switcher preview.

## Proposed Solution
Implement an app-wide blur effect that activates when the app enters the background and deactivates when it becomes active again. This will be done using the `UIApplicationDelegate` to handle app state changes and apply a blur effect to the app's main window.

## Implementation Details
1. Modify the `AppDelegate` class to handle app lifecycle events
2. Create a `UIVisualEffectView` with a blur effect
3. Add the blur view to the main window
4. Show the blur view when the app is about to enter the background
5. Hide the blur view when the app becomes active again

## Testing
- Verify that the app preview is blurred in the app switcher
- Test on various iOS versions and devices to ensure compatibility
- Ensure that the blur effect is applied and removed at the correct times during app lifecycle changes

**Comment by noob-programmer1** [comment]
I'm interested in implementing this feature. Please let me know  if there are any specific guidelines I should follow. Thanks!

**Comment by brindy** [comment]
Hello, thank you for using DuckDuckGo.

This feature is already available by enabling "Application Lock" via the in-app settings. It's not a blur, but it does hide the content of the browser.

Thanks again.

**Comment by noob-programmer1** [comment]
It hides the content only if you have switched to another app, but if in app preview it still shows the content if you haven't yet switched to any another app and just going thorugh the opend apps in app preview . Attacting video for reference.

Uploading 0188FFD0-53FA-4145-A704-45204A45C403 (1).mp4…

Uploading 0188FFD0-53FA-4145-A704-45204A45C403 (1).mp4…

**Comment by noob-programmer1** [comment]
It hides the content only if you have switched to another app, but if in app preview it still shows the content if you haven't yet switched to any another app and just going thorugh the opend apps in app preview . Attacting video for reference.


https://github.com/user-attachments/assets/92ae3cb8-d263-4fe9-86dd-cb8393e2735d
