### ISSUE TITLE
Sharing with tile

### ISSUE THREAD

**Issue by vonProteus** [duckduckgo/iOS#3222]
can you please add this to the browser
screens from safari
![IMG_7559](https://github.com/user-attachments/assets/5cefd8b5-2743-47de-b7a5-42955a2ca8c5)
and add things action
![IMG_7560](https://github.com/user-attachments/assets/60566fc2-6c58-456e-95c7-0e3114ae70d0)

**Comment by awaan05** [comment]
Can you please elaborate more?

**Comment by vonProteus** [comment]
in ddg when i click "add to things" i get 
![IMG_CE7016ABABC5-1](https://github.com/user-attachments/assets/6008176c-b0f8-4f05-b3b5-2e6943a7de02)
i would like like that "new to-do" was prefilled with page title

**Comment by awaan05** [comment]
Thanks for clarify, will try to fix that.

**Comment by adityarajpt** [comment]
@awaan05 If this is still open I can take this up, I wanted to contribute to this project and don't see any other issue or bug to pick

**Comment by adityarajpt** [comment]
@vonProteus does this works when you do the same action from safari?

**Comment by vonProteus** [comment]
> @vonProteus does this works when you do the same action from safari?

Yes

**Comment by adityarajpt** [comment]
@awaan05  I looked around, seems like solution to this problem is conforming `Link` to `UIActivityItemSource` and then it will take care of providing title from activityViewControllerLinkMetadata method, lmk if you want me to work on this.
thanks

**Comment by awaan05** [comment]
@adityarajpt sure!
