### ISSUE TITLE
Fire button not removing URL

### ISSUE THREAD

**Issue by mattlikespie** [duckduckgo/iOS#3246]
This issue has popped up again. When using the fire button, the "flame" effect trips, but the url is not removed and can be accessed using the Go button (bottom right). 

DDG v7.132.0.3
iOS 17.6.1 (21G93)

_Originally posted by @mattlikespie in https://github.com/duckduckgo/iOS/issues/2435#issuecomment-2292626582_

**Comment by brindy** [comment]
Hi @mattlikespie - Can you check this on a more recent version please?  Please re-open if you're still seeing it.  Thanks!
