### ISSUE TITLE
Site rating doesn't refresh if change protocol from `http` to `https`

### ISSUE THREAD

**Issue by tsekityam** [duckduckgo/iOS#328]
### Steps to reproduce behavior
1. Visit `http://www.ust.hk` with the app
1. Check the site rating, the encryption type is *unencrypted*
1. Change the url to `https://www.ust.hk`
1. Check the site rating again, and the encryption type is still *unencrypted*

### Expected behavior 
The encryption type should be either *forced*, *encrypted* or *mixed*

### Actual behavior 
The encryption type is still *unencrypted* after I changed to visit the site with `https`

### What is the version of the duckduckgo app you are running?
v7.6.1 on iPhone 6 Plus with iOS 11.4

**Comment by brindy** [comment]
Thanks for this! Will review soon.
