### ISSUE TITLE
Future plan for Translation on the app?

### ISSUE THREAD

**Issue by carloshmartins** [duckduckgo/iOS#3293]
I noticed that the app doesn't have translation within the Browser.

Is there a plan to add this functionality?

I use 24/7 DDG, and lacking this is the only reason I use other browser.

Maybe with the new Translation API from Apple eventually?

**Comment by brindy** [comment]
Hi, we do talk about this from time to time but so far have not found a way to do it that respects privacy, data and battery. :) 

That new Apple API might well be the way forward.  

Will close this out, but please be assured it's definitely on our radar.  Thanks

Tracking this internally [here](https://app.asana.com/0/715106103902962/1208331423616620/f).
