### ISSUE TITLE
Searching numbers

### ISSUE THREAD

**Issue by fgei** [duckduckgo/iOS#34]
If I enter a number on the search bar the app loads that as a URL rather then making a search with the number as the query

input: "3"
result: "http://3/"
I'd expect: "https://www.duckduckgo.com/?ko=-1&kl=wt-wt&q=3"

is this the expected result?

**Comment by subsymbolic** [comment]
Thanks for reporting this! This is now fixed, PR https://github.com/duckduckgo/iOS/pull/35.
