### ISSUE TITLE
Widget Colors are Broken in iOS 18 Accented Mode

### ISSUE THREAD

**Issue by jfebrian** [duckduckgo/iOS#3498]
**Summary**
The DuckDuckGo iOS browser widgets display broken colors when the home screen is in Accented Widget mode on iOS 18. This majorly affects the usability of the widgets as it is no longer usable.

**Screenshots**
1. Search Widget
![Screenshot 2024-10-28 at 23 17 28](https://github.com/user-attachments/assets/e7ae2ceb-bbaa-4cf6-a197-d4e2da8ba94b)

2. Passwords Widget
![Screenshot 2024-10-28 at 23 17 52](https://github.com/user-attachments/assets/dd3e47fd-7b06-4049-867b-f64ea8f89a6b)

3. Medium Favorites Widget
![Screenshot 2024-10-28 at 23 19 51](https://github.com/user-attachments/assets/5440af15-9bc6-4f16-ba4f-e5329c3c2cea)

4. Large Favorites Widget
![Screenshot 2024-10-28 at 23 20 21](https://github.com/user-attachments/assets/f0b7461b-d03f-4fa0-b1d6-750026cf75e5)

5. VPN Widget
![Screenshot 2024-10-28 at 23 18 24](https://github.com/user-attachments/assets/fcb35275-5c30-4087-95f3-0995fc0bc607)

**Root Cause**
On iOS 18, when users apply the accented theme on the home screen, all widgets will enter `accented` mode. In this mode, all SwiftUI Colors will be white by default, this also affects images. Now, `Rectangle().fill()` is used in most of the widgets, causing them to have a massive white square that makes them unusable. _I have not confirmed this behavior in any Apple documentation, but based on my experimentation this is the case_. I suspect that Apple wants to add colors on top of the white colors, and developers are required to adjust the opacity and rendering mode of the UI elements in the widgets.

**Solution**
Apple has provided two methods to solve this issue, [`widgetAccentable(_:)`](https://developer.apple.com/documentation/swiftui/view/widgetaccentable(_:)) and [`widgetAccentedRenderingMode(_:)`](https://developer.apple.com/documentation/swiftui/image/widgetaccentedrenderingmode(_:)). Complete information can be read on the documentation, but to explain it simply, here's what I found about the main functionality of those two methods:

1. **`widgetAccentable(_:)`**: We use this to decide whether a view and its children should be accented or not, note that the value set for this function in the parent view will override its children. However, what I found is that even if we set this to false, SwiftUI Color will still default to the white color as explained above. So we still need to play around with the opacity and accented for the widget to look good.
2. **`widgetAccentedRenderingMode(_:)`**: This one is more straightforward, it's to change the accented rendering mode for images. There are many different modes, I applied `fullColor` on most of the images to ensure there is no change in colors in the main images.

**Results**

I have prepared a [branch in my forked repository](https://github.com/jfebrian/DuckDuckGo-iOS/tree/jfebrian/fix-widgets-on-accented-ios-18) to fix this issue. Please let me know if it's okay to create a pull request to this repository.

1. Search Widget
![Screenshot 2024-10-28 at 23 37 53](https://github.com/user-attachments/assets/b1ad3a24-11cc-416c-a96a-3a059c0c1dd3)

2. Passwords Widget
![Screenshot 2024-10-28 at 23 38 28](https://github.com/user-attachments/assets/a5c46369-48ff-42b6-a40f-980762e96c4d)

3. Medium Favorites Widget
![Screenshot 2024-10-28 at 23 41 14](https://github.com/user-attachments/assets/8ca1d42c-540a-4a22-849c-03d2bfd5a5c4)

4. Large Favorites Widget
![Screenshot 2024-10-28 at 23 40 43](https://github.com/user-attachments/assets/0bb8e064-11c1-48c1-a3bb-4d1fc7a26d9e)

5. VPN Widget
![Screenshot 2024-10-28 at 23 38 50](https://github.com/user-attachments/assets/cf76b8bf-7580-4b42-962d-63a3b0c046d1)

**Disclaimer**
I found the issue when I was looking around the code base as I'm currently applying for a Senior iOS Engineer position in DDG. I did some minor cleanup of the SwiftUI code along the way to make it easier to read and maintain. Also, I'm not sure which colors or modes the designer would like, so I tried to keep everything as close as possible to the original design. Feedback is very much appreciated ^^

**Comment by brindy** [comment]
Hi,

Thanks for this, we're aware.  Part of it is being blocked on using Xcode 16 in our Github CI (due to some test breakage, etc), but that is resolving soon so we should be able to fix this then. 

Tracking internally at https://app.asana.com/0/715106103902962/1208407714247766/f

Good luck :)
