### ISSUE TITLE
Associated Domains / Universal Linking

### ISSUE THREAD

**Issue by kApp-Oliver** [duckduckgo/iOS#3499]
Hey there, 

I know this isn't a bug fix or an issue currently listed on your 'Help Wanted' section but I'd like to run the idea past you all anyway.

I've actually [pushed a commit](https://github.com/duckduckgo/iOS/commit/4ac5a0ad0c6d0a7ca48b95bf603305eb65e27db4) with the required changes but I'm unable to do much testing due to the requirement for this to be tested with a signed app on a physical device.

### Description

Currently if a user installs the DDG app but doesn't set it as the default browser, any `DuckDuckGo.com` links they interact with will open within their current system browser (Safari for example).

---
### Proposed Solution

Implement associated domain / app links support for the `DuckDuckGo.com` domain name.
This will ensure users who have the app installed will automatically be taken to the DDG app when they tap on a system-wide `DuckDuckGo.com` link.

This should ultimately drive more app users and could even give the app another opportunity to prompt for 'Default Browser' enablement.

For context, I have some something similar on another app that ultimately lead to our monthly active users increasing from ~50k to nearly ~400k.

---
### Implementation Details

- Add the `com.apple.developer.assoicated-domains` entitlement array and add `applinks:duckduckgo.com`
- Implement `application(_ application: UIApplication, continue userActivity: NSUserActivity,...`
- Unwrap the provided webpageURL and utilise existing logic from `application(_ app: UIApplication, open url: URL,...`
- Raise a request to get a valid `apple-app-site-association` configuration file created at `https://duckduckgo.com/.well-known/apple-app-site-association`

---
### Testing

Testing this functionality requires a physical device with access to the DDG Apple Developer team.
You'll need to do the following to test without using the production `apple-app-site-association` file -

- Enable `Settings -> Developer -> Associated Domains Development`
- Add a `?mode=developer` flag to the `applinks:duckduckgo.com` record
- You could consider adding the above to the debug build scheme...
- Utilise a tool like Proxyman or Charles proxy to intercept app traffic (Make sure you trust the SSL certificate on your device)
- Enable 'SSL Proxying' for `https://duckduckgo.com/.well-known/apple-app-site-association` and return a valid configuration file

If the above is setup correctly you should be able to tap on any 'DuckDuckGo.com' link on other apps and be taken directly to the DuckDuckGo app instead of your system browser.

**Comment by kApp-Oliver** [comment]
> Hey there,
> 
> I know this isn't a bug fix or an issue currently listed on your 'Help Wanted' section but I'd like to run the idea past you all anyway.
> 
> I've actually [pushed a branch](https://github.com/kApp-Oliver/DDG_iOS/tree/olliebates/universal_linking) with the required changes but I'm unable to do much testing due to the requirement for this to be tested with a signed app on a physical device.
> 
> ### Description
> Currently if a user installs the DDG app but doesn't set it as the default browser, any `DuckDuckGo.com` links they interact with will open within their current system browser (Safari for example).
> 
> ### Proposed Solution
> Implement associated domain / app links support for the `DuckDuckGo.com` domain name. This will ensure users who have the app installed will automatically be taken to the DDG app when they tap on a system-wide `DuckDuckGo.com` link.
> 
> This should ultimately drive more app users and could even give the app another opportunity to prompt for 'Default Browser' enablement.
> 
> For context, I have some something similar on another app that ultimately lead to our monthly active users increasing from ~50k to nearly ~400k.
> 
> ### Implementation Details
> * Add the `com.apple.developer.assoicated-domains` entitlement array and add `applinks:duckduckgo.com`
> * Implement `application(_ application: UIApplication, continue userActivity: NSUserActivity,...`
> * Unwrap the provided webpageURL and utilise existing logic from `application(_ app: UIApplication, open url: URL,...`
> * Raise a request to get a valid `apple-app-site-association` configuration file created at `https://duckduckgo.com/.well-known/apple-app-site-association`
> 
> ### Testing
> Testing this functionality requires a physical device with access to the DDG Apple Developer team. You'll need to do the following to test without using the production `apple-app-site-association` file -
> 
> * Enable `Settings -> Developer -> Associated Domains Development`
> * Add a `?mode=developer` flag to the `applinks:duckduckgo.com` record
> * You could consider adding the above to the debug build scheme...
> * Utilise a tool like Proxyman or Charles proxy to intercept app traffic (Make sure you trust the SSL certificate on your device)
> * Enable 'SSL Proxying' for `https://duckduckgo.com/.well-known/apple-app-site-association` and return a valid configuration file
> 
> If the above is setup correctly you should be able to tap on any 'DuckDuckGo.com' link on other apps and be taken directly to the DuckDuckGo app instead of your system browser.

I've just spotted your documentation around cloning DuckDuckGoDeveloper.xcconfig for external developer builds. 🤦 I'll give that a go and get this running properly on my own device as well.

**Comment by brindy** [comment]
Hi,

Thanks for this but the default browser entitlement actually prohibits us from associating the app with any domain. 

> Apps that have the [com.apple.developer.web-browser](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_web-browser) managed entitlement may not claim to respond to Universal Links for specific domains.

See: [Preparing your app to be the default web browser ](https://developer.apple.com/documentation/xcode/preparing-your-app-to-be-the-default-browser)

Very much appreciate the thought and effort though. ❤️

**Comment by kApp-Oliver** [comment]
> Hi,
> 
> Thanks for this but the default browser entitlement actually prohibits us from associating the app with any domain.
> 
> > Apps that have the [com.apple.developer.web-browser](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_web-browser) managed entitlement may not claim to respond to Universal Links for specific domains.
> 
> See: [Preparing your app to be the default web browser ](https://developer.apple.com/documentation/xcode/preparing-your-app-to-be-the-default-browser)
> 
> Very much appreciate the thought and effort though. ❤️

Well I never knew that! 😅
Everyday is a learning day haha!

I’ll keep my eye out for any on-going bugs that I could help with. I’m keen to get involved more going forward in my spare time 🙂

Cheers
Ollie

**Comment by brindy** [comment]
Sure, please just open an issue first like you did here rather than creating a PR straight away as it might be something we already track internally. Thanks :)

**Comment by kApp-Oliver** [comment]
Sure thing! Sounds good. Cheers!
