### ISSUE TITLE
bookmark title is clipping few letters

### ISSUE THREAD

**Issue by pastmaster007** [duckduckgo/iOS#416]
**Issue:**
bookmark title is clipping few letters refer below image

https://i.imgur.com/uDZuZeN.png

**Comment by bwaresiak** [comment]
Closing this, as explained in https://github.com/duckduckgo/iOS/pull/417

> This problem is caused by system font - internally we use Proxima Nova fonts that are proprietary, and with these, problem does not exist (as can be seen in the APpStore version of the app).
