### ISSUE TITLE
Choose Theme (light or dark) when there is no Internet connection

### ISSUE THREAD

**Issue by juliopovedacs** [duckduckgo/iOS#442]
Hello,

I wanted to know if the next behavior is expected from the app or if it is a bug:

 I downloaded the app, and when I opened it for the first time, I had no Internet connection. The screen that asks users to choose a theme (light or dark) did not appear.

I ask this question because I am able to change the app's theme when I am offline in settings. Thus, the screen asking users to choose a theme the first time they open the app should appear regardless if he/she has an Internet connection or not.

Thank you.

**Comment by bwaresiak** [comment]
Thanks for taking time to write in about this and sorry for the confusion. 

Rest assured, this isn't a bug. We are currently testing changes to our onboarding screen in a phased approach and only show the new option to some installations. We hope to finish our refinements and make the changes available to everyone soon.

I hope that clears things up, let us know if you have any other questions.

**Comment by juliopovedacs** [comment]
Thank you!
