### ISSUE TITLE
Target=“_Blank” HTML code is not honored

### ISSUE THREAD

**Issue by old-username-mcx** [duckduckgo/iOS#448]
Within the iOS app, any links that have HTML code with `target=“_blank”`, the app does not honor it. Works fine on other web browsers like Safari, etc.

App version: 7.21.0
Device model: iPhone XS & iPad Pro 3rd Gen
iOS version: 12.3.1
Reproduce: click a link with the specified HTML property `target=“_blank”`
Expected behavior: Open a new tab to the link
Actual behavior: Takes the current tab to the link

**Comment by bwaresiak** [comment]
This is now tracked internally at: https://app.asana.com/0/856498667320406/1127319456014388

I've managed to reproduce this issue, we will tackle it as soon as we have some resources available. 

Thank you for your feedback!

**Comment by brindy** [comment]
A fix for this has been merged and will be in a future release.  Thanks for raising it @mcspadden  and thanks @roop  for the fix.
