### ISSUE TITLE
HTTP Basic Authentication isn't supported

### ISSUE THREAD

**Issue by salty-horse** [duckduckgo/iOS#467]
Similar bug for the Android app, where this was already implemented: https://github.com/duckduckgo/Android/issues/383

Using 7.24.0.

When visiting a website that requires Basic Authentication, you immediately get a 401 Unauthorized error.

**Comment by bwaresiak** [comment]
This is now tracked internally at https://app.asana.com/0/856498667320406/1133521518040402

Thank you for your report!

**Comment by brindy** [comment]
Basic support is now in the app!  Thanks for raising this @salty-horse.
