### ISSUE TITLE
Make building easier for external developers using xcconfig

### ISSUE THREAD

**Issue by roop** [duckduckgo/iOS#479]
Currently, the Xcode project file includes DuckDuckGo's Apple developer id. An external contributor (i.e. someone outside of the DuckDuckGo development team) needs to change the account id, app id and app group names before the app can be compiled. The external contributor should also take care to exclude these changes from the PR being worked upon.

It would make life easier for external contributors if these variables (development team id, app id and app group prefix) can be specified in a separate xcconfig file. The xcconfig file should not be included in the git repo, and a template can be included in place of that.

If you think this is worth doing, I can work on a PR for this.

**Comment by brindy** [comment]
Hi, this would be great, thanks.  Please go ahead and start on this if you'd like.  We're going to track this internally at https://app.asana.com/0/414709148257752/1138781991854351.

Thanks!
