### ISSUE TITLE
Where is your mystery unit converter?

### ISSUE THREAD

**Issue by ghost** [duckduckgo/iOS#488]
Hello developers,

This is a question related to your website, not iOS app.

May I ask where is your mystery unit converter(s)? And how can I summon it?

Yesterday, typing `1 foot to meters` made your mystery unit converter show up. Today that's not working.

Would you please help make them available in easier way? The question to a good engineer is: if you have those things, why you make it _extremely hard_ for the users to find them?

**Comment by bwaresiak** [comment]
Hello,

Generally what you've described should work. Reaching unit converter is as easy as searching for it: https://duckduckgo.com/?q=unit+converter It should also automatically appear for the related queries - like the one you mentioned.

If you have issues related to search results (like missing unit converter for a particular query), there is an option to send us feedback about it:
- On the web, 'Send feedback' button located in lower-right corner.
- On the mobile, 'Send feedback' button located at the very bottom of the results page.

List of all instant answers is available here: https://duck.co/ia

Hope that helps! Please ask if you have follow up questions (or reach out directly to website team by sending them feedback).

**Comment by ghost** [comment]
To @bwaresiak and DuckDuckGo developers:

I apologize for my question. I was not calm when I typed it. Then, for embarrassment, I deleted my account.

Thank you for your hard work.

**Comment by bwaresiak** [comment]
Thanks for the follow up - worry not, no offense taken 😃 

Since this issue is not related to iOS I'm going to close it. Fell free to reopen if needed.
