### ISSUE TITLE
Looking to contribute to this project.

### ISSUE THREAD

**Issue by sindhugudivada** [duckduckgo/iOS#489]
Are you guys looking for any open source contributors. I 'm fairly new to open source and would love to learn and contribute.

**Comment by bwaresiak** [comment]
Hello, glad to hear that!

Please refer to [our contributing guidelines](https://github.com/duckduckgo/iOS/blob/develop/CONTRIBUTING.md) for more information about that. Unfortunately we usually don't have many issues open that can be picked up by external contributors, but if you have something in mind feel free to open one and we can discuss it.

**Comment by bwaresiak** [comment]
I'm going to close this, but feel free to re-open in case you have questions.
