### ISSUE TITLE
Include app version number in iOS system settings

### ISSUE THREAD

**Issue by bwaresiak** [duckduckgo/iOS#497]
Internal reference: https://app.asana.com/0/856498667320406/1145008528714429

**Description**

Goal is to include app version number in iOS system settings. Example from Test Flight:

![settings](https://user-images.githubusercontent.com/2865434/66864971-99718f80-ef96-11e9-913a-5f760cad84ba.png)

**Comment by nehayward** [comment]
I should be able to manage this! Is it okay if I start on a PR for this.

**Comment by bwaresiak** [comment]
@nehayward Thanks for volunteering, but we already have someone working on that in #500
