### ISSUE TITLE
Please drop duckduckgo support for iOS

### ISSUE THREAD

**Issue by ghost** [duckduckgo/iOS#517]
I have discovered very important details.
I have sold all my iOS devices.

https://forums.macrumors.com/threads/ios-is-terrible-about-privacy.2205813/
https://community.signalusers.org/t/suggestion-to-drop-signal-support-for-ios/9893

You can’t set up and use iPhone offline. You always have to do an internet activation in the setup window first. If you reset the software, internet activation is required again. iPad, iPod touch, Apple TV and Apple Watch same problem. The worst thing is if Apple shuts down the servers then you will never be able to use the iOS devices again.

Also when installing apps (locally installed by PC) you have to connect to the App Store the first time you start it. You are completely bound to Apple. Offline use is not possible.

During use it can connect over 100 undocumented Apple domains.

– my $150 or High-End Android device does not have this limitation. Can always set up and use offline.

Not to forget, iOS has a built-in remote keylogger from Apple. Every keypass is sent to Apple server!

In general, developers don’t like iOS. It is extremely limited and always set against the user.
Best duckduckgo iOS will no longer support, because iOS and the other Apple systems are harmful platform for developers and users.

It is better to support Android or Android without google service and Linux than iOS. Users always benefit first and it is the most sustainable solution.

Please will not support iOS devices and the Apple platform again. It is really a harmful platform.

**Comment by brindy** [comment]
(We note this is a deleted account).

Thanks for your feedback.  We are committed to providing privacy protection for our users who use the iOS platform for whatever reason.

If you have problems with the iOS platform it would be best to contact Apple directly.

Thanks again for your support.

**Comment by patsybond172** [comment]
During use it can connect over 100 undocumented Apple domains. Also when installing apps (locally installed by PC) you have to connect to the App Store the first time you start it. You are completely bound to Apple. Offline use is not possible. like this [https://patsybond172.github.io/kitchen-cabinets](https://patsybond172.github.io/kitchen-cabinets) or this [https://github.com/patsybond172](https://github.com/patsybond172)

**Comment by janicetyler** [comment]
Not to forget, iOS has a built-in remote keylogger from Apple. Every keypass is sent to Apple server! 
[https://github.com/janicetyler](https://github.com/janicetyler)
[https://github.com/janicetyler/wood-kitchen-cabinets](https://github.com/janicetyler/wood-kitchen-cabinets)
[https://janicetyler.github.io/wood-kitchen-cabinets](https://janicetyler.github.io/wood-kitchen-cabinets/)

**Comment by headStyleColorRed** [comment]
Jesus... are these bots writing the comments or what's going on?
