### ISSUE TITLE
Give amoled dark theme.

### ISSUE THREAD

**Issue by ghost** [duckduckgo/iOS#520]
For battery life, and visual consistency with iOS 13 dark mode.

**Comment by bwaresiak** [comment]
Hello @jt-k 

We provide both 'Dark' and 'Light' themes in-app. You can navigate to the Settings and choose either one, or pick 'System Default' to make our app match the iOS theme dynamically.

Could you please elaborate what is that is missing for you?

Thanks!

**Comment by ghost** [comment]
I strike my claim that an amoled dark mode saves more battery than a "dark gray" mode, apparently the battery life savings between these two modes are negligible. For visual aesthetic, I suppose it would be a matter of satisfying a niche user interest. But apps like Reddit, Instagram, and Twitter give their users an option for a true black mode, or an amoled mode, as it is sometimes called. I would hope that you folks consider giving your users this theming option. Thank you.

**Comment by bwaresiak** [comment]
Thanks for the explanation. I've shared your feedback internally with Product and Design teams.

I'm going to close it for now, but feel free to reopen if you have more comments or questions.
