### ISSUE TITLE
DDGPersistentContainer.defaultDirectoryURL returns nil when using an ExternalDeveloper.xcconfig 

### ISSUE THREAD

**Issue by KevinVitale** [duckduckgo/iOS#530]
The `GROUP_ID_PREFIX` value in `ExternalDeveloper.xcconfig` is not imported, causing a crash when `DDGPersistentContainerdefaultDirectoryURL.defaultDirectoryURL()` implicitly unwraps a `nil` value.

Just a few minutes into the codebase, but the fix appears simple: interpolate `Global.globalIdPrefix` as part of `Database.Constants.databaseGroupID`.

A PR with this change is incoming.

**Comment by bwaresiak** [comment]
Closing as it's resolved. Thanks @KevinVitale
