### ISSUE TITLE
Disable video autoplay

### ISSUE THREAD

**Issue by jplock** [duckduckgo/iOS#540]
Can an option be added to disable video autoplay?

**Comment by bwaresiak** [comment]
Hello,

Thank you for the feedback. I've shared this with the product team. I'll update this issue again once we have made a decision.

Internal task URL: https://app.asana.com/0/856498667320406/1153727682934211

**Comment by brindy** [comment]
We're still tracking this internally.  I will add a note to try and get a decision.  Thanks for raising this and sorry it's took a long time to respond.

**Comment by msmasters624** [comment]
Any update?
