### ISSUE TITLE
Tab Switcher: the switcher background can be tapped in lieu of 'Done' bar button to dismiss

### ISSUE THREAD

**Issue by KevinVitale** [duckduckgo/iOS#545]
The tab switcher continually gives me the impression that I can tap the background to return to the tab I was at (e.g., dismiss the switcher as I would if I tapped the 'Done' button).

This might sound silly, but I'm constantly tapping the background expecting this behavior. Not sure if this is my own problem or not, so I'm opening this (**low-priority**) issue for feedback, as well as submitting a PR for the team to try out.

<hr/>
Alternately, swapping the location of the Settings-Cog nav-bar button and the Done tab-bar button may be enough.  
  

In iOS, bar buttons with state transitions are more often found at the top of the screen, for example: 
 - a search field with a results controller and a _Cancel_ button that dismisses the search modal; 
 - when you're editing a list in a table view and the _Edit_/_Done_ nav-bar button

**Comment by brindy** [comment]
As per comment on the PR - this area is about to get some TLC and we don't want to change the UX at this time.  Thanks for the suggestion!
