### ISSUE TITLE
Traslation to others languages

### ISSUE THREAD

**Issue by ArtCC** [duckduckgo/iOS#554]
Hi!

I have started to translate the app to Spanish from Spain and I see that there are many texts that do not exist in the Localizable.string file and I have started to add them, do you accept the translation to languages? :)

Regards,

Arturo.

**Comment by bwaresiak** [comment]
@ArtCC we also think localizing the app is a great idea and have it on the roadmap, but we'd prefer to develop this functionality internally along with the process to keep it up to date when new strings are introduced.

Nonetheless, thank you for suggesting that and showing interest in contributing. :)
