### ISSUE TITLE
UI/Snapshot Tests are broken

### ISSUE THREAD

**Issue by albsala** [duckduckgo/iOS#559]
UI/Snapshot Tests are broken in develop. Something about the Onboarding, Site Ranking, and Network Offenders must have been changed and UI Tests were not updated apparently. It's a quick fix so I'm preparing a PR in case it's useful for you.

**Comment by brindy** [comment]
Hello,

We are now tracking this internally at: https://app.asana.com/0/414709148257752/1158699016458265

Since there was no further PR forthcoming I'm going to close this out.

Thanks for your continued use of our app!
