### ISSUE TITLE
Background audio automatically stops

### ISSUE THREAD

**Issue by lleheny0** [duckduckgo/iOS#572]
Audio from the browser will stop after about a minute if the app is not focused. Switching to another tab and keeping that tab open will allow the audio from the first tab to continue playing. When switching to another app, switching to the home screen, or locking the phone, the audio will stop after a minute.

Unsure if this is intended behavior.

**Comment by brindy** [comment]
Hi, thanks for reaching out.

Unfortunately this is how iOS behaves for apps which aren't designated as providing "background audio", and as a browser, we don't fall in that category.  We might be able to to [enable](https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio) it, but I need to do some investigation first to see if it breaks any App Store guidelines.  Additionally, users may be expecting this behaviour so we don't want to make a change that could affect a lot of people negativity.

We're going to track this internally at: https://app.asana.com/0/392891325557410/1167663516937428

Thanks again.

**Comment by brindy** [comment]
We tried adding the background audio settings but it doesn't appear to have any effect, I'm afraid.  We're going to close this for now - hopefully we can work out the problem eventually or it'll be fixed by iOS.
