### ISSUE TITLE
DuckDuckGo url spoofing not fixed

### ISSUE THREAD

**Issue by ghost** [duckduckgo/iOS#584]
Hi I reported a url spoofing vulnerability on iOS in a different but it got marked as duplicate even thought it’s still reproducible it’s the case number is #788957

**Comment by bwaresiak** [comment]
Hello @epicodertime 

Could you clarify what vulnerability you are talking about and where it was reported (which system this case number is from)? 

Thank you

**Comment by ghost** [comment]
Hi sorry for not specifying this vulnerability is on the iOS app and I reported via duckduckgo hackerone program which is the case number for the report on hackerone and a Address Bar spoofing is a critical vulnerability in which any attacker can spoof the address bar to a legit looking website but the content of the web-page remains different from the Address-Bar display of the site.

**Comment by ghost** [comment]
If you need additional information feel free to ask me

**Comment by bwaresiak** [comment]
@epicodertime thanks for clarification, I will check this out and come back to you. :)

**Comment by ghost** [comment]
And by the way would you like a proof of consent video of the vulnerability on the iOS app

**Comment by brindy** [comment]
Hi @epicodertime, thanks for reporting this.  We very much value input from the community so appreciate the time taken to bring this to our attention.

HackerOne marked this as a duplicate of another report that was considered "informative" only and therefore of no significant risk.  We have also reviewed this internally and have come to the same conclusion. 

As such, we'll be closing this out and won't be creating a fix for this specific issue at this time.

Thanks again.
