### ISSUE TITLE
“Keep Me Signed In” feature does not work with twitter

### ISSUE THREAD

**Issue by superusercode** [duckduckgo/iOS#593]
After turning this feature on, logging into twitter, and then clearing my history/pressing the fire button I've found that the browser refuses to save my twitter login even when I force a login on the desktop site.

**Comment by brindy** [comment]
Hi - thanks for letting us know. 

We were already aware of this and are working to improve that feature. 

There is a new release coming in the next few days with something we are calling Fireproof Websites which will give users more control over which websites the app keeps data for. I’ve tested it with Twitter and it seems to be working fine.  

Keep an eye out for it and let us know how you get on. Thanks!
