### ISSUE TITLE
Header 'Core-Swift.h' not found

### ISSUE THREAD

**Issue by CharlotteFallices** [duckduckgo/iOS#594]
在下面这段来自`module.modulemap`的代码中:
```Swift
module Core.Swift {
    header "Core-Swift.h"
    requires objc
}
```
未能成功找到`Core-Swift.h`

------
==
The Issue is under Artistic License 2.0.
That's all.

**Comment by brindy** [comment]
Hello, thanks for reaching out to us and for your continued use of our app.

Please follow the instructions in the README for how to build the app.  

If you have any further problems, please re-open this issue.

Thanks!
