### ISSUE TITLE
Favorite icon menu doesn't dismiss.

### ISSUE THREAD

**Issue by daisuke-t-jp** [duckduckgo/iOS#601]
- App version
  - [9e486fc007c1d861f5ef4357325759138c597031](https://github.com/duckduckgo/iOS/commit/9e486fc007c1d861f5ef4357325759138c597031)
- iOS version
  - iOS 13.3
- Steps to reproduce the bug
  1. Open home(include favorite)
  1. Long press to favorite icon for showing menu.
  1. Touch favorite icon to load.
- Expected behavior
  - Dismiss menu.
- Actual behavior
  - Showing menu.

---

<img src="https://user-images.githubusercontent.com/45647069/77229666-819bd880-6bd2-11ea-81b6-2998a37839ce.gif" width="300">

**Comment by brindy** [comment]
Thanks, we're going to track this internally at: https://app.asana.com/0/414709148257752/1167663516937426
