### ISSUE TITLE
Unnecessary scrolling happened in Feedback

### ISSUE THREAD

**Issue by daisuke-t-jp** [duckduckgo/iOS#604]
- App version
  - 7.41.1
- iOS version
  - iOS 13.3.1
- Steps to reproduce the bug
  - Open feekback text input screen.
  - Switch other app(keyboard showing).
  - Back DuckDuckGo app.
- Expected behavior
  - No change on screen.
- Actual behavior
  - Unnecessary scrolling happened

![FD836F14-6BC1-4D8A-9148-A8B2990679CB](https://user-images.githubusercontent.com/45647069/77375895-32ac9980-6db2-11ea-9180-c02c41be3e2c.gif)

**Comment by brindy** [comment]
Thanks for raising this.  We're tracking this internally at https://app.asana.com/0/414709148257752/1169706165059549 and I'm going to review it shortly.
