### ISSUE TITLE
The input suggestion function does not work with FindInPage.

### ISSUE THREAD

**Issue by daisuke-t-jp** [duckduckgo/iOS#605]
# Summary
The input suggestion function does not work with FindInPage.
Therefore, the user cannot select Japanese Kanji.
I think the same problem occurs in Chinese.

# Information
- App version
  - 0894e4103b511c789accd09a28e4e78ba94f1cd1
- iOS version
  -  iOS 13.3
- Steps to reproduce the bug
  1. Open FindInPage.
  1. Input japanese.
- Expected behavior
  - Input suggestions are displayed on keyboard.
- Actual behavior
  - No suggestions are displayed on keyboard.

# Screenshots
The Input suggestions function working in NavigationBar.
<img width="320" alt="navi" src="https://user-images.githubusercontent.com/45647069/77440725-fb7ace80-6e2b-11ea-8802-24c5fc181aa8.png">

But it doesn't work on FindInPage.
<img width="320" alt="findinpage" src="https://user-images.githubusercontent.com/45647069/77441879-4e08ba80-6e2d-11ea-989f-dfcd1bb3f3f2.png">

**Comment by brindy** [comment]
Thanks for this, we're tracking it internally at https://app.asana.com/0/414709148257752/1168763499025419 

I'll review your PR this weekend.  Thanks!
