### ISSUE TITLE
The browser should hide page contents if locked

### ISSUE THREAD

**Issue by netvl** [duckduckgo/iOS#611]
Many applications which have the “lock” feature (e.g. password managers or messengers like Signal) blur or otherwise hide their contents when they are not active, otherwise it is possible to see what’s inside them without unlocking them on the application manager screen:
![7B05B25C-871C-433A-9ABC-CA66E8FB80A3](https://user-images.githubusercontent.com/280456/78188175-a1c66580-7424-11ea-9684-0e075acfb71e.jpeg)

 You can see on the picture above that Bitwarden and Telegram hide their contents on the app selection screen, but DuckDuckGo does not, even though it is actually configured to request unlocking upon activation. I’d expect DDG do the same thing as other similar applications.

**Comment by brindy** [comment]
Hi - thanks for the clear explanation.  

We're tracking this internally at https://app.asana.com/0/392891325557410/1169498296439393 and will get a fix out soon (probably next release).

**Comment by netvl** [comment]
That’s an awesomely quick response, thank you! I really like your browser, thanks for the great work! :)
