### ISSUE TITLE
Retain cycle in PrivacyProtectionOverviewController

### ISSUE THREAD

**Issue by Johennes** [duckduckgo/iOS#617]
Noticing this on current `master` (`53c29feb96f1dbb52c94112d0a9be9aebf33bc92`). Each time the privacy overview modal is opened (by tapping the icon on the left side of the address bar) a new instance of `PrivacyProtectionOverviewController` (and all it's referenced objects) gets stuck in memory.

The root cause is that `InteractivePopRecognizer` holds a strong reference to the controllers navigation controller, which in turn holds a strong reference to the controller itself. So the controller strongly references the gesture recognizer, which strongly references the navigation controller which strongly references the controller.

![Screenshot 2020-04-08 at 15 28 40](https://user-images.githubusercontent.com/1137962/78791237-e8313c80-79af-11ea-8633-e09c07c9e32d.png)

A suitable fix would be to make the `navigationController` property `unowned`.

```
private class InteractivePopRecognizer: NSObject, UIGestureRecognizerDelegate {
    
    unowned var navigationController: UINavigationController!
```

This seems safe because the recognizer only lives as long as the privacy overview controller lives and the navigation controller cannot get deallocated before its child controllers are.

**Comment by brindy** [comment]
Thanks for this! We're tracking this internally at https://app.asana.com/0/392891325557410/1170462535379951 and will make the fix soon.

**Comment by bwaresiak** [comment]
Since #618 is merged and released, I'm closing this off. Thanks!
