### ISSUE TITLE
Desktop site feature loads mobile layout

### ISSUE THREAD

**Issue by Johennes** [duckduckgo/iOS#624]
This is the equivalent of https://github.com/duckduckgo/Android/issues/768. I'm opening this against the iOS app as well because I was able to demonstrate a potential fix in the iOS code (see below).

Some sites with a responsive layout look the same regardless of whether the desktop site was requested. This can be a problem when certain features are hidden on smaller screens which makes the "request desktop site" feature less useful in those case.

One example is stackoverflow.com.

This is default layout:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-16 at 22 09 03](https://user-images.githubusercontent.com/1137962/79502140-8025ca80-802f-11ea-8c64-e038758f6923.png)

This is the layout after requesting the desktop site:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-16 at 22 09 11](https://user-images.githubusercontent.com/1137962/79502153-8320bb00-802f-11ea-9fdf-2e75b1c90aee.png)

Both look the same because the page uses a responsive design. 

This doesn't happen on the Firefox Android app and, as mentioned in https://github.com/duckduckgo/Android/issues/768#issuecomment-614755040, Firefox appears to be forcing a desktop viewport (980px wide) when the desktop site is requested.

In the Firefox app, this switch is made inside the layout engine itself (see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1106905)). For the DuckDuckGo iOS app, I think it might be possible to achieve the same by forcing a desktop viewport via a user script.

The diff below is a _quick hack_ to demonstrate what I mean:

```
diff --git a/DuckDuckGo/TabViewController.swift b/DuckDuckGo/TabViewController.swift
index 4f166fa..922ef4b 100644
--- a/DuckDuckGo/TabViewController.swift
+++ b/DuckDuckGo/TabViewController.swift
@@ -364,6 +364,25 @@ class TabViewController: UIViewController {
         if #available(iOS 13, *) {
             webView.configuration.defaultWebpagePreferences.preferredContentMode = tabModel.isDesktop ? .desktop : .mobile
         }
+
+        reloadScripts()
+
+        if tabModel.isDesktop {
+            webView.configuration.userContentController.addUserScript(WKUserScript(
+                source: """
+                    let content = 'width=980px';
+                    let viewport = document.querySelector('meta[name=viewport]');
+                    if (viewport) {
+                        viewport.content = content;
+                    } else {
+                        viewport = document.createElement('meta');
+                        viewport.name = 'viewport';
+                        viewport.content = content;
+                        document.getElementsByTagName('head')[0].appendChild(viewport);
+                    }
+                    """,
+                injectionTime: .atDocumentEnd, forMainFrameOnly: true))
+        }
     }
```

With this in place stackoverflow.com loads in a desktop-like layout:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-16 at 22 09 43](https://user-images.githubusercontent.com/1137962/79502751-56b96e80-8030-11ea-9fa9-28d92029f8d1.png)

I haven't evaluated the potentially broader implications of such a user script but I wanted to share my findings to put this up for discussion.

**Comment by Johennes** [comment]
I'd be happy to submit a proper pull request if that is appreciated. Not going to invest more time before the way forward is not agreed upon of course. 🙂

**Comment by brindy** [comment]
Hi @Johennes - we discussed this internally when we first added desktop mode (the team was much smaller then) and landed on the side of not trying to change a website's responsiveness, though we acknowledge that might be the reason someone switches to desktop mode.  I think @cmonfortep already said we'd discuss it as it's probably best for us to make the same change in both places so we'll have that chat and get back to you.

Thanks for being proactive!

**Comment by Johennes** [comment]
👌

Sorry for double-posting. I originally found this on my Android device but then it turned out easier to investigate it on the iOS app due to prior knowledge. 🙈

**Comment by brindy** [comment]
Thanks again for this, and sorry for the long delay in keeping you up to date.  This is still on our radar internally, but I don't expect us to make the change any time soon as we're not seeing a great deal of feedback around this issue.  Certainly if that changes (especially in light of now being able to be set as default browser) it'll end up being prioritised.  Thanks again!

**Comment by patsybond172** [comment]
Some sites with a responsive layout look the same regardless of whether the desktop site was requested. This can be a problem when certain features are hidden on smaller screens which makes the "request desktop site" feature less useful in those case. [https://patsybond172.github.io/kitchen-cabinets](https://patsybond172.github.io/kitchen-cabinets) or this [https://github.com/patsybond172](https://github.com/patsybond172)

**Comment by mayassuarez172** [comment]
Same for the comment its Some sites with a responsive layout look the same regardless of whether the desktop site was requested. 
[https://github.com/mayassuarez172](https://github.com/mayassuarez172)
[https://github.com/mayassuarez172/blue-kitchen-cabinets](https://github.com/mayassuarez172/blue-kitchen-cabinets)
[https://mayassuarez172.github.io/blue-kitchen-cabinets](https://mayassuarez172.github.io/blue-kitchen-cabinets)

**Comment by janicetyler** [comment]
Good Idea's  we discussed this internally when we first added desktop mode (the team was much smaller then) and landed on the side of not trying to change a website's responsiveness 
[https://github.com/janicetyler](https://github.com/janicetyler)
[https://github.com/janicetyler/wood-kitchen-cabinets](https://github.com/janicetyler/wood-kitchen-cabinets)
[https://janicetyler.github.io/wood-kitchen-cabinets](https://janicetyler.github.io/wood-kitchen-cabinets/)

**Comment by lucialam172** [comment]
Sorry for double-posting. I originally found this on my Android device but then it turned out easier to investigate it on the iOS app due to prior knowledge 
[https://github.com/lucialam172/dark-kitchen-cabinets](https://github.com/lucialam172/dark-kitchen-cabinets)
[https://github.com/lucialam172](https://github.com/lucialam172)
[https://lucialam172.github.io/dark-kitchen-cabinets](https://lucialam172.github.io/dark-kitchen-cabinets)
