### ISSUE TITLE
Multiple back buttons in privacy protection view

### ISSUE THREAD

**Issue by tsekityam** [duckduckgo/iOS#628]
## App version
7.44.0.0

## Device model
iPhone XR

## iOS version
13.4.1
    
Steps to reproduce the bug
1. Click Privacy Protection button on the left of the URL
2. Navigate to the sub pages of the session

![IMG_8593](https://user-images.githubusercontent.com/3814422/80197012-ab707100-8650-11ea-8dd5-6dd394ed34a7.PNG)
![IMG_8594](https://user-images.githubusercontent.com/3814422/80197024-af9c8e80-8650-11ea-8b5f-a3f293421566.PNG)
![IMG_8595](https://user-images.githubusercontent.com/3814422/80197027-b0cdbb80-8650-11ea-831b-44fd7f48220b.PNG)
![IMG_8597](https://user-images.githubusercontent.com/3814422/80197034-b1665200-8650-11ea-984c-76528f1e7d3e.PNG)
![IMG_8596](https://user-images.githubusercontent.com/3814422/80197037-b1fee880-8650-11ea-9113-0c996bbf0816.PNG)

Expected behavior
There is only 1 back button on each sub pages

Actual behavior
There are 2 back button on each sub pages

**Comment by brindy** [comment]
Fixed by #629
