### ISSUE TITLE
Safe area not covered at the bottom on "Find in Page"

### ISSUE THREAD

**Issue by Lascorbe** [duckduckgo/iOS#638]
**App version:** 
7.45.0.0

**Device model:** 
iPhone 11 Pro

**iOS version:** 
iOS 13.4.1

**Steps to reproduce the bug:**
- Go to find "Find in Page"
- Search something
- Scroll down, or hide keyboard (on iPad Pro)

**Expected behavior:**
You cannot see the website content behind the home indicator/safe area

**Actual behavior:**
You can see the website content behind the home indicator/safe area

![IMG_DBC9AADD7F58-1](https://user-images.githubusercontent.com/1515520/82117956-26bad380-9774-11ea-89bf-3f2fe4b3276e.jpeg)

**Comment by brindy** [comment]
Tracking this internally at https://app.asana.com/0/inbox/392891325557408/1195769562482255/1195785915763848

**Comment by pankova** [comment]
Hello! 🙂 Could I help you with it as Hacktoberfest participating?

**Comment by brindy** [comment]
Hi @pankova - yes, thank you.

**Comment by brindy** [comment]
Hey @pankova - do you have a timescale for your fix?   Thanks!

**Comment by pankova** [comment]
> Hey @pankova - do you have a timescale for your fix?   Thanks!

Hello! Yes, I faced signing trouble. It seems, I couldn't provide group id. If there is some other way to build project or some test configuration data for external developers, it would be great!

**Comment by brindy** [comment]
Please see the `Developer details` section in the readme.  Let me know if you have any further problems.  Thanks!

**Comment by brindy** [comment]
Hi @pankova - how are you getting on?

**Comment by pankova** [comment]
> Hi @pankova - how are you getting on?

Hello! Sorry, I'm a little overworking, but I plan to finish it!

**Comment by brindy** [comment]
Hi @pankova - just wondering if you've been able to make any progress?

Since Hacktoberfest finishes on the 31st and we have another PR ready for this fix, can you please submit your PR by the end of October 30.

Or if you're unable to finish this by then, that's fine, we just need to know.

Thanks.

**Comment by pankova** [comment]
> Hi @pankova - just wondering if you've been able to make any progress?
> 
> Since Hacktoberfest finishes on the 31st and we have another PR ready for this fix, can you please submit your PR by the end of October 30.
> 
> Or if you're unable to finish this by then, that's fine, we just need to know.
> 
> Thanks.

Hello! I have made PR some minutes ago :)
Sorry for waiting! 🙏

**Comment by brindy** [comment]
Fixed by #761 - thank you @pankova !
