### ISSUE TITLE
Add an option to disable search bar autofocus

### ISSUE THREAD

**Issue by Lascorbe** [duckduckgo/iOS#639]
**App version:** 
7.45.0.0

**Device model:** 
iPhone 11 Pro

**iOS version:** 
iOS 13.4.1

**Steps to reproduce the issue:**
- Force close the app if it's open
- Open the app
- Search bar becomes first responder (gets focused)

**Expected behavior:**
You cannot disable this from settings

**Actual behavior:**
You are able to disable this behaviour from settings

**Comment by bwaresiak** [comment]
Hello @Lascorbe 

Did you try navigate to Settings -> Keyboard and turn off the 'App Launch' option? I did try this and it worked for me with 7.45.0.0 for the scenario you've described.

If this doesn't work for you, I'd appreciate info about following settings:
- New Tab (Top/Centered, Favorites).
- Auto Clear (On/Off).
- App Lock (On/Off).

Thanks!

**Comment by Lascorbe** [comment]
That's what I was looking for, I can't believe I didn't see that before. Thank you!
