### ISSUE TITLE
Layout problem in privacy dashboard

### ISSUE THREAD

**Issue by tsekityam** [duckduckgo/iOS#640]
### What did I do
1. Visit a broken site, e.g. http://12321sdljfghashgf.com/
2. Open privacy dashboard

### What did I see
![image](https://user-images.githubusercontent.com/3814422/82196326-206f5780-992c-11ea-939d-9d5b8febbb8b.png)

### What do I expect
No text overlap at the end of the dashboard

### What did I use
iPhone XR with iOS 13.1.1
DuckDuckGo 7.46.0.0

**Comment by brindy** [comment]
Thanks for reporting this.

Does this only happen in the error state (ie when it says "Uh-oh, that didn't work.") ?

**Comment by tsekityam** [comment]
Yes, it only happens in error state. Look like we will not enter [this function](https://github.com/duckduckgo/iOS/blob/2dabc9d8b27d83f8192636f4512525d5e9bcf77c/DuckDuckGo/PrivacyProtectionFooterController.swift#L118) to show/hide footer view when we are in error state.

I am preparing a patch to hide both `gatheringView` and `scoresView` in storyboard by default, such that the view will only be visible if above function is executed. How do you think about this patch?

**Comment by brindy** [comment]
Merged, thanks!
