### ISSUE TITLE
Fireproof not working

### ISSUE THREAD

**Issue by mickaphd** [duckduckgo/iOS#642]
I just tried to fireproof a website I use a lot (https://my.nextdns.io/) to stay connected even after pressing the fire button and it's not working, I'm always disconnected. Have no idea why.

**Comment by brindy** [comment]
Hi, thanks for letting us know.  I've had a look and it's not clear why this is happening.  The way fireproofing works is by saving the cookies a website sets.  We appear to be doing this, but it still isn't working.  It might be they are saving some data elsewhere which we don't save - we only have limited access to a website's data stores via WKWebView's API.  If you have any ideas I'd be glad to hear them.  Thanks!

**Comment by samsymons** [comment]
@brindy I took a closer look at this one out of curiosity, after running into a similar issue.

NextDNS sets all of its session cookies with the domain `api.nextdns.io`, whereas `my.nextdns.io` is the URL which gets saved when Fireproofing.

```
(lldb) po cookies.filter { $0.domain.contains("nextdns") }
▿ 3 elements
  - 0 : <NSHTTPCookie
	version:1
	name:pst
	value:<redacted>
	expiresDate:'2021-07-14 19:27:38 +0000'
	created:'2020-07-14 19:27:38 +0000'
	sessionOnly:FALSE
	domain:.api.nextdns.io
	partition:none
	sameSite:none
	path:/
	isSecure:TRUE
	isHTTPOnly: YES
 path:"/" isSecure:TRUE isHTTPOnly: YES>
  - 1 : <NSHTTPCookie
	version:1
	name:sid
	value:<redacted>
	expiresDate:'(null)'
	created:'2020-07-14 19:27:38 +0000'
	sessionOnly:TRUE
	domain:.api.nextdns.io
	partition:none
	sameSite:none
	path:/
	isSecure:TRUE
	isHTTPOnly: YES
 path:"/" isSecure:TRUE isHTTPOnly: YES>
  - 2 : <NSHTTPCookie
	version:1
	name:__cfduid
	value:<redacted>
	expiresDate:'2020-08-13 19:27:12 +0000'
	created:'2020-07-14 19:27:12 +0000'
	sessionOnly:FALSE
	domain:.nextdns.io
	partition:none
	sameSite:lax
	path:/
	isSecure:TRUE
	isHTTPOnly: YES
 path:"/" isSecure:TRUE isHTTPOnly: YES>

(lldb) po logins.isAllowed(cookieDomain: ".nextdns.io")
true

(lldb) po logins.isAllowed(cookieDomain: ".my.nextdns.io")
true

(lldb) po logins.isAllowed(cookieDomain: ".api.nextdns.io")
false
```

**Comment by brindy** [comment]
Thanks @samsymons !

That explains a lot.  We've been talking internally about this situation where the cookies are set on some kind of authentication domain and are planning to address the problem in the near future.

Thanks again for diving in!

**Comment by brindy** [comment]
We're working on this internally here: https://app.asana.com/0/72649045549333/1184658016368940

It will probably fixed on Android first with a follow up on iOS, but it's on the radar.
