### ISSUE TITLE
Launch screen has bottom space on devices with home indicator

### ISSUE THREAD

**Issue by fassko** [duckduckgo/iOS#650]
I saw that the main image in `LaunchScreen.storyboard` has a bottom to Toolbar which is hidden.

<img width="1648" alt="Pasted_Image_09_06_2020__22_56" src="https://user-images.githubusercontent.com/29482/84193736-9470cb80-aaa4-11ea-834b-3405369a7f3b.png">

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-09 at 22 52 57](https://user-images.githubusercontent.com/29482/84193819-b4a08a80-aaa4-11ea-931f-04719f25cd14.png)

**Comment by bwaresiak** [comment]
Hello, 

We are in the process of remaking the Launch Screen and this is already fixed on the feature branch that will be merged to develop soon.

Nonetheless, thank you for pointing that out :-)
