### ISSUE TITLE
Settings partially support Dynamic Type

### ISSUE THREAD

**Issue by fassko** [duckduckgo/iOS#651]
I bumped text size to the max and used Bold Text.

![image](https://user-images.githubusercontent.com/29482/84193959-f2051800-aaa4-11ea-8a8c-3b0c82f58dcd.png)

I recently wrote a blog post about it https://kristaps.me/embracing-dynamic-type/

**Comment by brindy** [comment]
Hi @fassko,

Thanks for this!  We are tracking it internally here: https://app.asana.com/0/392891325557410/1198492230691825

I saw your recent tweet about this earlier today as well. I really want us to support this properly, but I think it will involve close collaboration with our design team to make sure we don't affect any UI/UX.  We've just release a fairly big change to support transitions so my hope is that it will make this easier as well.

Please correct me if I'm wrong but it appears that the best way to support this is by using the built in text styles and specifying font metrics for them as per our blog post here: https://kristaps.me/custom-font-dynamic-type/

I think we have quite a varied amount of text styles in the app so it would likely take some effort (mainly from the design team) to match them to specific text styles.

I notice you can check the "supports dynamic type" option when specifying a custom font/style in interface builder. Do you know what the implications of that are?  

Thanks!

**Comment by fassko** [comment]
Hi @brindy,

Thank you for reaching out! ;)

I'm the DuckDuckGo app user myself and dealing with Dynamic Type in a different project I understood that the DuckDuckGo app doesn't support. People using non-default font sizes is 40% so it is a big percentage.

I understand that you need to convey to your design guidelines and it would require some work for your designers to check it.

Easiest is to use the built-in font styles, those ones scale correctly. But it is not so hard to scale custom ones.

> I notice you can check the "supports dynamic type" option when specifying a custom font/style in the interface builder. Do you know what the implications of that are?

If you check that checkbox then the app will scale fonts, just use the Environment Overrides to test it.

I actually started to improve this in the DuckDuckGo app but understood that you are using closed fonts and it requires some work internally which I can't access...

**Comment by brindy** [comment]
This has been open for a while with no progress, am going to close it out for now.  Thanks.

**Comment by fassko** [comment]
Yes sorry, I couldn't find time for this. Running my own startup takes all the time I have.

**Comment by brindy** [comment]
No problem! Hope that is going well for you. :)
