### ISSUE TITLE
Bottom bar does not appear when scrolling up slowly

### ISSUE THREAD

**Issue by fassko** [duckduckgo/iOS#652]
Is it a bug or a feature? :P

**Comment by bwaresiak** [comment]
Hello,

We want to match Safari's behavior and reveal bars only when users swipe upwards with some momentum (basically reveal bars in a scenario when website is still scrolling after finger is lifted from the screen - technically scroll view in this case is "decelerating"). There are additional ways to reveal bars: reaching top of the page, bouncing when at the bottom of the page, tapping top or bottom of the screen, navigating to different page.

But, if only the bottom bar is hidden (and top one is revealed), then it's a bug. 

Thank you for bringing this up, in case my explanation is not clear or you encounter scenario that does not match what I've described please share the details and we will investigate. :-)

**Comment by fassko** [comment]
OK, now I understand. In that case, it is a feature. :)
