### ISSUE TITLE
Can‘t watch YoutTube videos in fullscreen (iPad)

### ISSUE THREAD

**Issue by JonathanKrug** [duckduckgo/iOS#675]
Hi, in the DDG app it is currently not possible to watch YouTube (I know it's from Google😅) videos in full screen view. The fullscreen button is greyed out. (As you can see in picture 1)

![image](https://user-images.githubusercontent.com/31386997/87444536-33826900-c5f7-11ea-8856-934b166c9a3f.jpeg)

Since it works fine in Safari (see picture 2), it seems to be a bug in the DDG app.

![image](https://user-images.githubusercontent.com/31386997/87444582-41d08500-c5f7-11ea-823d-60fcff27e23c.jpeg)

Device: iPad Pro 12.9" 3rd generation
Software: iPadOS 13.5.1
App-Version: 7.48.1.0

**Comment by brindy** [comment]
Hi Jonathan,

Thanks for getting in touch!  Sadly, we are aware of this and are looking in to fixing it if we can. In the mean time you can use the browsing menu (The ... button top right) to select "mobile" mode and you should be good from there.

Thanks,
Chris

________________________________
