### ISSUE TITLE
Lost header when navigating from tabs list

### ISSUE THREAD

**Issue by fassko** [duckduckgo/iOS#683]
I had a couple of times this situation when the header toolbar disappeared. I was navigating from tabs list where I changed layout removed tab.

![image](https://user-images.githubusercontent.com/29482/88193541-77541e80-cc46-11ea-93a1-070687eabe12.png)
https://www.imore.com/best-ad-blockers-iphone-and-ipad
![image](https://user-images.githubusercontent.com/29482/88193932-e3368700-cc46-11ea-95e0-727aa7861e75.png)

**Comment by brindy** [comment]
Hi @fassko - thanks for bringing this to our attention.  Since then we've released a small update to the UI to better support iPads and I suspect we fixed this during that release.  I'm going to close, but please re-open if you are still seeing the issue.  Thanks!

**Comment by fassko** [comment]
Thanks @brindy I will check out if it has been fixed.
