### ISSUE TITLE
Tests fail below iOS 13

### ISSUE THREAD

**Issue by daisuke-t-jp** [duckduckgo/iOS#687]
Hi,

Some tests fail below iOS 13.
I checked with Xcode 11.6 (11E708).

<img width="640" alt="exception" src="https://user-images.githubusercontent.com/45647069/89286117-9b731f00-d68c-11ea-9808-aa2d879142dc.png">

---

These tests throw exceptions.
(These function is called even below iOS 13.)

https://github.com/duckduckgo/iOS/blob/4b28b97cd76c9e5775113b2606f4a17713a6eca5/DuckDuckGoTests/CookieStorageTests.swift#L38-L56

---

The test fails because `appUserDefaults.currentThemeName`  is not `systemDefault`.

https://github.com/duckduckgo/iOS/blob/4b28b97cd76c9e5775113b2606f4a17713a6eca5/DuckDuckGoTests/AppUserDefaultsTests.swift#L84-L89

https://github.com/duckduckgo/iOS/blob/4b28b97cd76c9e5775113b2606f4a17713a6eca5/DuckDuckGo/AppUserDefaults.swift#L69-L84

---

Thanks.

**Comment by brindy** [comment]
Fixed by #688 - thanks again!
