### ISSUE TITLE
Text overflows in dialogs on smaller screen devices

### ISSUE THREAD

**Issue by DjCantor** [duckduckgo/iOS#696]
Hi, 

I've found this issue regarding smaller screen devices:

App version: most recent
Device model: iPhones with 4.7 and 4 inch screens
iOS version: 13.6
Steps to reproduce the bug: first start of the application, going through the tutorials while browsing
Expected behavior: text bubbles wrap the text
Actual behavior: the text overflows on small screen devices.

![Simulator Screen Shot - iPhone SE (1st generation) - 2020-08-16 at 19 49 58](https://user-images.githubusercontent.com/3447937/90340659-1aa41380-dffa-11ea-8fc3-f54506f080d4.png)
Here you can't see the whole text:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-16 at 19 49 47](https://user-images.githubusercontent.com/3447937/90340646-0b24ca80-dffa-11ea-8300-3071fd497b88.png)

**Comment by brindy** [comment]
Hi @DjCantor - am I right in saying you built and ran this yourself rather than installing from the App Store?  It looks as though the commercial font we use is missing which explains why the line heights are out.

**Comment by DjCantor** [comment]
Hi @brindy : yes, you are right, and I didn't notice that the fonts would be those commercial fonts. Sorry for the false alarm!

**Comment by brindy** [comment]
no problem! Thanks for reaching out :)
