### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/iOS#7]
I think the red while on brand is a bit alarmist in terms of color theory. We should arguably ride the private browsing wave on this and try to pull of a dark theme of some sort. I think Design can help a lot here.

**Comment by subsymbolic** [comment]
Some design input would be great, I think a dark theme would look good too.

**Comment by subsymbolic** [comment]
I've done a simple swap of the orange for a dark grey, you should see this in the upcoming release. Subsequent releases will start switching over to the new designs.
