### ISSUE TITLE
Support for adblock/adblock filter lists

### ISSUE THREAD

**Issue by superusercode** [duckduckgo/iOS#712]

**Comment by superusercode** [comment]
While VPNs and DNS level adblockers can offer a similar experience (especially since dns switching is native in iOS 14) I prefer that cosmetic filters that are possible with browser native adlocking.

**Comment by brindy** [comment]
Hi - thanks for the suggestion.  We are currently using Tracker Radar to provide best in case tracker blocking and don't have any plans to extend the app to support ad-blocking at this time. (We of course block ads that track you though)
