### ISSUE TITLE
Hardcoded app ids on the WidgetExtension and OpenAction targets

### ISSUE THREAD

**Issue by gholias** [duckduckgo/iOS#713]
I cloned the project today and followed the steps on the readme about setting up the External Developer Details in `ExternalDeveloper.xcconfig` and the project could not compile because of the hardcoded Ids on those targets.

This is the error message:
```
error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

		Embedded Binary Bundle Identifier:	com.duckduckgo.mobile.ios.Widgets
		Parent App Bundle Identifier:		com.felipeoliveira.duckduckgo.mobile.ios
```

The solution is pretty simple: Making the extension targets to use of the var **$APP_ID**

I will send a PR shortly.

**Comment by brindy** [comment]
Thanks for this!
