### ISSUE TITLE
opening app store links has a weird modal

### ISSUE THREAD

**Issue by superusercode** [duckduckgo/iOS#715]

**Comment by quanganhdo** [comment]
Second this. Also, it’d be great if the Yes/No buttons are renamed to Open/Cancel to make the dialog more user friendly.

**Comment by brindy** [comment]
Hi @superusercode thanks for this.  It's been fixed and will be in an upcoming next release.

@quanganhdo - we're doing a copy review of the entire app, so I'll raise your comment with that team as a point of interest.

Thanks!
