### ISSUE TITLE
Shortcut to invoke 1password from any website

### ISSUE THREAD

**Issue by quanganhdo** [duckduckgo/iOS#719]
I love that in iOS 14 it’s possible to set DuckDuckGo as the default browser. One of the missing pieces, however, is 1password support. 

I created a simple shortcut to invoke 1password from any website. It’ll switch to the 1password app and fill in the second-level domain (e.g. “github” in “gist.github.com”) as the search keyword so that you can quickly copy the credentials. It works really well when [the Password prompt doesn’t show up correctly for some websites](https://twitter.com/quanganhdo/status/1306328556662857734) 

The shortcut is here: https://www.icloud.com/shortcuts/0991450311e0463cb9869c6025d6d618

You’ll need the free [Scriptable app](https://scriptable.app/) installed

**Comment by brindy** [comment]
Thanks for this tip! Hopefully folk have had enough time to read this now.
