### ISSUE TITLE
Any issues for outside contributors?

### ISSUE THREAD

**Issue by jaroslavas** [duckduckgo/iOS#728]
As you may know, tomorrow [hacktoberfest](https://hacktoberfest.digitalocean.com) starts, where people are asked to contribute to open source projects. Do you have any tasks that could be done by outsiders willing to help?

**Comment by brindy** [comment]
There's been a couple - just need to keep an eye on the issues list and jump in when you can.  tbh, it's an awkward time for us as we're usually just recovering from whatever Apple has done in September and this year was particularly ... difficult. :) 

We're open to suggestions as well, but as a guide bug fixes are more desirable than features.  Anything that requires a serious UI/UX change will not likely be accepted as it will need to be approved by our design and product teams.

Thanks for your interest!
