### ISSUE TITLE
Add clone tab feature

### ISSUE THREAD

**Issue by JonathanKrug** [duckduckgo/iOS#762]
Hi,

The possibility to clone a tab is already available in many browsers, so it would be very cool if the DDG app could do that too.

I'm interested in contributing! I have already developed the feature locally. Only the localization is still missing.
![Screen-Recording-2020-10-27-at-1](https://user-images.githubusercontent.com/31386997/97290868-70dad180-1849-11eb-9673-a061a03fffdf.gif)

**Comment by bwaresiak** [comment]
@JonathanKrug thanks for the suggestion. As we support bookmarklets, you can add bookmark/favorite with URL set to `javascript:window.open(window.location.href);` and use it to duplicate currently open tab. 

Browsing menu is already quite full (which is especially visible on smaller phones), so we would rather avoid adding new entries to it, unless it is strongly justified. 

Thanks for your interest in contributing. :)
