### ISSUE TITLE
Add couple request/suggestions?

### ISSUE THREAD

**Issue by iGlitch** [duckduckgo/iOS#787]
### **DARK MODE**

Any plans to add a dark mode switch to websites? No, I don't mean waiting for websites to update their CSS to detect and support dark mode but actually force it. (Like Dark Reader addon)

Firefox for iOS can do this, seems like an inversion thing because it affects the images of some sites, but it's better than nothing.

### **Timer for Face ID**

Maybe add a timer for the next time passcode/Face ID is required after minimizing app. (Also someting FF can do)

### **Remove Set as Default Browser if already set as default browser**

This one should be pretty self explanitory.

Anywhere I can contribute translations?

Hopefully an iOS update comes out soon allowing to add website shortcuts for other browsers to the home screen without having to use widget ^_^

Sorry for all the comparisons to other browser but it's just great features I'd like to see this have.
Thanks :)

**Comment by brindy** [comment]
Hi! 

Thanks for the Dark Mode and Face ID suggestions, I’ll make a note of those internally.

As for set as default, unfortunately we can’t explicitly tell if the user has set it or not.

RE translations - we use an external service for that, but if you have found specific problems please create an issue with them listed (in English and the language in question) along with the proposed change and we can feed that back to the translation service.

Regarding Home Screen shortcuts - you can sort of do that now by using the Shortcut app and adding the shortcut to the Home Screen. This is how I use Twitter with our app. If you have a different default browser but want to create a shortcut to DuckDuckGo you can use our URL scheme:

`ddgQuickLink://example.com`


Hope that helps. Thanks again.
