### ISSUE TITLE
"back" button or swipe right jumps to top of previous site

### ISSUE THREAD

**Issue by mothe-at** [duckduckgo/iOS#789]
**App version:** 7.59.0.0
**Device model:** iPhone 11 Pro
**iOS version:** 14.2

**Steps to reproduce the bug:**
When I hit the "back" button or swipe right to go back to the previous site, the previous site then jumps to the top of the page.
For instance, I read a newspaper, scroll down the headlines some while and the tap a link to read the full article. When I then swipe right or hit back, the previous site jumps to the top.

**Expected behavior:**
When hitting back button or swipe right, the view should be where it have being left off.

**Actual behavior:**
See above, the page view on the referring page lands at the top of the page.
This happens on ALL sites I have tried. And this does NOT happen when I use the same sites on Safari or Chrome.

![DDG-back-problem](https://user-images.githubusercontent.com/19708050/100553623-1e993000-328f-11eb-8dc0-967d5f36ff06.gif)

**Comment by brindy** [comment]
I'm going to close this out and track this via #730 - we need a solution that can fix all these cases as they're all related.
