### ISSUE TITLE
Favourites sometimes get an incorrect icon

### ISSUE THREAD

**Issue by st3fan** [duckduckgo/iOS#794]
Sometimes favorites on the home screen get the incorrect icon assigned. Below you can see that the first and last icon in the top row have an incorrect icon. The first is CNN, whose icon is now that of The NY Times and The NY Times has the icon of The Guardian. The rest of the icons are correct.

There are no clear steps to reproduce this. It did add more favourites to my home screen recently and I have a feeling that increases the frequency of incorrect icons.

![IMG_0917](https://user-images.githubusercontent.com/28052/101777327-52126080-3ac0-11eb-8c2b-927d832dbe64.jpg)

If I see something in the icon / home screen code that could cause this, would you take a speculative patch for this?

**Comment by brindy** [comment]
Thanks for raising this @st3fan - we've been aware of it internally and we think #792 fixes it.  Feel free to check out develop and see if that works for you, but if not I'm doing a release today anyway so should be on the App Store in the next day or two.  Thanks!

**Comment by st3fan** [comment]
Great I will give it a try when it ships. Sorry, I did not see #792 when I posted this.

**Comment by brindy** [comment]
No problem at all! Thanks for being vigilant  :D

**Comment by st3fan** [comment]
I do want to add my own analysis to this issue: it is speculative because this is hard to debug without adding some diagnostics to the code - I did not put in the time to actually debug this on a device.

There is a possibility that the root cause here is actually around UICollectionViewCell re-use. I think the `FavoriteHomeCell` is properly re-used, but it may not be properly initialized on re-use or cleared when the system is done with it.

The `FavoriteHomeCell` is ultimately initialized in `updateFor`, but the code paths leading to that call can all exit because of various conditions, which results in `updateFor` not being called. The cell that is then put in the `UICollectionView` may not be fully initialized, and is hanging on to _old_ data from when the cell was used previously.

Looking at the code, the data in a re-used cell that has the biggest chance of hanging around and not being properly initialized is the image.

Second, it is probably a good idea to implement the `prepareForReuse()` method in the `FavoriteHomeCell` and then explicitly let go of all the data that the cell is hanging on to. The `self.link` but also the data the UI elements point to, specifically setting `self.iconImage.image` to `nil`.

(There is no guarantee that you will get a cached cell back for the same `IndexPath`. So if rebuilding/loading these images is a concern then I would probably delegate that part to a small image caching library.)

This `prepareForReuse()` call is part of the re-use logic. You can skip it, if it is there it may definitely make cell re-use problems more obvious, because there won't by any change that old data is there. If after that there still is a problem with image loading then I think cells will then probably appear blank or have the "fake" icon.

 What do you think?

**Comment by brindy** [comment]
Hey @st3fan - sorry for not replying it's been a busy few months. 

Are you still seeing this problem? I can't say I've noticed it.  

As such I'm going to close this out, but if you have solid steps to reproduce and/or want to create a PR to fix, please re-open. 

Thanks!
