### ISSUE TITLE
Potential memory leak in BloomFilterWrapper

### ISSUE THREAD

**Issue by s3cur3** [duckduckgo/iOS#806]
The `BloomFilterWrapper` doesn't clean up the `BloomFilter` it allocates on init. As best I can tell, this is mostly a theoretical leak—in the app, the `BloomFilterWrapper` is currently retained for the lifetime of the program. If this ever were *not* the case though (as is the case in the test suite), the allocated `BloomFilter` would be leaked.

If you'd like, I can submit a pull request for [the (tiny) fix](https://github.com/s3cur3/iOS/commit/03e97382e28f3da99c4a6b7a4814273c2810d570).

**Comment by brindy** [comment]
Sorry for the delay in replying.  Yes, feel free to submit a PR.  As you say the filter is tied to the the lifetime of the app anyway so no rush.  Thanks!

**Comment by brindy** [comment]
Tracking internally here: https://app.asana.com/0/392891325557410/1199935106721785

**Comment by samsymons** [comment]
Closing this as #833 was merged, thanks @s3cur3!
