### ISSUE TITLE
It will just open the file instead of downloading it in the HTML a label

### ISSUE THREAD

**Issue by acdzh** [duckduckgo/iOS#807]
Hello! I met a problem and I am not sure whether this is a feature or just a bug.

![image](https://user-images.githubusercontent.com/32260125/104589990-a606fb00-56a5-11eb-8636-5a3f1cf050a2.png)

```html
<!DOCTYPE html>
<html>
<head>
  <title>test</title>
  <script>
    downloadData = function() {
      const a = window.document.createElement('a');
      a.download = 'data.zip';
      a.href = '/data.zip';
      a.click();
    };
  </script>
</head>
<body>
  <button onclick="downloadData();">download</button>
</body>
</html>
```

on safari, it looks like this:

![image](https://user-images.githubusercontent.com/32260125/104589902-84a60f00-56a5-11eb-869e-907a95ac49e5.png)

but on duckduckgo, it just open it:
![image](https://user-images.githubusercontent.com/32260125/104589956-9982a280-56a5-11eb-8af5-a7f6c9877191.png)
![image](https://user-images.githubusercontent.com/32260125/104589967-9c7d9300-56a5-11eb-9075-47791eaebb79.png)

Is this normal? Thanks.

**Comment by acdzh** [comment]
OS version: iOS 14.0 on iPhone 11 Por Max
App version: DuckDuckGo 7.61.5.0

**Comment by brindy** [comment]
Hi, thanks for this.  We're aware that we're not handling downloads very well at all at the moment and already have a project underway to address it, which we're tracking internally here: https://app.asana.com/0/414709148257752/1145004832722773

 I'll share your feedback with the rest of the team though. 

Thanks again!
