### ISSUE TITLE
Can't build the app due to SwiftLint type_name violation

### ISSUE THREAD

**Issue by sukhrobkhakimov** [duckduckgo/iOS#843]
**Steps to reproduce:**
1. Pull the `develop` branch.
2. Build the app.
3. The app shows a compile-time error: `Type Name Violation: Type name should only contain alphanumeric characters: 'WidgetViews_Previews' (type_name)`.

**Possible solutions:**
1. `struct WidgetViews_Previews: PreviewProvider { // swiftlint:disable:this type_name`.
2. Add the rule below to `.swiftlint.yml` to allow underscores.
```
type_name:
  allowed_symbols: "_"
```
3. Just remove the `_` and make sure you never use it. **Best Solution**

**Comment by samsymons** [comment]
Hey @sukhrobkhakimov!

Are you on an older version of SwiftLint? This was [resolved in 0.35.0](https://github.com/realm/SwiftLint/blob/master/CHANGELOG.md#enhancements-16).

**Comment by sukhrobkhakimov** [comment]
Hi @samsymons 

Thanks for your quick reply. Yeah, I am currently using 0.34.0. But, the point is to avoid using `_` in Swift code entirely. I wonder why the SwiftUI team keeps naming things inconsistently.

**Comment by samsymons** [comment]
FWIW I agree with you @sukhrobkhakimov, I'm not a fan of underscores either. 😄
