### ISSUE TITLE
Automatically trim trailing whitespace from empty lines

### ISSUE THREAD

**Issue by sukhrobkhakimov** [duckduckgo/iOS#844]
I see the codebase has a lot of leading whitespace in empty lines. I suggest checking `Including whitespace-only lines` under `Preferences -> Text Editing -> Editing -> Automatically trim trailing whitespace` in Xcode and add this rule to `STYLEGUIDE.md` for others to follow.

**Comment by brindy** [comment]
Note added to style guide, thanks!
