### ISSUE TITLE
Missing snapshot when swiping back

### ISSUE THREAD

**Issue by aigarssilavs** [duckduckgo/iOS#846]
When swiping back to previous page the snapshot sometimes does not appear. Seemingly the navigation bar visibility when performing the swipe back action has to match the bar visibility when snapshot was initially taken for it to appear. May be related to #789 

**App version:** 7.62.1.0
**iOS version:** 14.2
**Device:** iPhone X
**Steps to reproduce the bug:** 
1. Open any web page
2. Tap on any link to go to another web page
3. Scroll the web page:
 until the navigation bar is hidden if it was visible when performing (2)
 _or_ 
 until it's visible if it wasn't when performing (2)
4. Swipe back

**Expected behavior:** Snapshot of previous page is visible when swiping
**Actual behavior:** Snapshot pf previous page is not visible when swiping

![MissingSnapshot](https://user-images.githubusercontent.com/1329970/111468628-73719100-872e-11eb-8e19-fe2687b1cb52.gif)

**Comment by brindy** [comment]
Thanks for this! We're discussing it internally.

**Comment by brindy** [comment]
btw, I have a suspicion this is related to #730  

Let me know what you think.

Thanks!

**Comment by aigarssilavs** [comment]
Hi. Actually I've been working on #730 and - just checked - snapshots don't go missing after changes I've made to resolve it, so it appears that you're right. Fix for #846 will be a byproduct of the solution for #730.

#730 is a bit trickier that it may initially appear - decoupling the unobscured frame of the webView from the actual frame of the webView via safeAreaInsets introduces quite a lot of bugs. Haven't fixed them all at this time so it's not ready to be merged into production just yet, but the main issue is resolved and the most obvious bugs handled already.

You're welcome to take a look at it [here](https://github.com/aigarssilavs/duckduckgo-ios/tree/issue-730) if you wish. Any suggestions are welcome.

**Comment by brindy** [comment]
I'm going to close this out and track this via #730 - we need a solution that can fix all these cases as they're all related.
