### ISSUE TITLE
Excess keyboard spacing

### ISSUE THREAD

**Issue by aigarssilavs** [duckduckgo/iOS#847]
Unnecessary bottom content inset is applied to the web page when keyboard is presented.

**App version:** 7.62.1.0
**iOS version:** 14.2
**Device:** iPhone X
**Steps to reproduce the bug:** Select any textbox in any web page and scroll to the bottom of the page
**Expected behavior:** Scrolling stops when the bottom of the web page is reached
**Actual behavior:** Scrolling beyond web page content borders is allowed 

![ExcessKeyboardSpacing](https://user-images.githubusercontent.com/1329970/111471835-fea05600-8731-11eb-9050-da919450a65a.gif)

**Comment by brindy** [comment]
Thanks for this! If it's convenient and makes sense can you add a screenshot, please?

**Comment by aigarssilavs** [comment]
No problem. Here are the screenshots for of the same page as in the .gif in the original comment.

Keyboard dismisssed and view scrolled to the bottom:
![KeyboardDismissed](https://user-images.githubusercontent.com/1329970/111502962-002c4700-874f-11eb-9d20-e2ffef84ef9e.jpg)

Keyboard visible and view scrolled to the bottom:
![KeyboardVisible](https://user-images.githubusercontent.com/1329970/111502949-fc98c000-874e-11eb-939b-62140178a238.PNG)

**Comment by untalfranfernandez** [comment]
I've been checking this issue and it has to be related somehow with [this content offset change](https://github.com/duckduckgo/iOS/blob/develop/DuckDuckGo/MainViewController.swift#L234) when the keyboard is displayed. I've done some quick tests with different webpages removing that line and it seems to be working fine.

I'd propose a PR for that, but [that change](https://github.com/duckduckgo/iOS/pull/411) was introduced two years ago and I have the feeling of being missing something about it.

**Comment by brindy** [comment]
Thanks for diving in @untalfranfernandez

I guess that change was also made for the find in page UI we have.  If everything seems fine on iPhone 8, iPhone X and iPads without that line feel free to open a PR. :)

**Comment by brindy** [comment]
Hi, I don't think we're going to address this right now as it's generally not a big issue for most users. If you feel like having another shot in the future, please feel free to reopen or create a new issue with your PR.   Thanks again for getting in touch!
