### ISSUE TITLE
[Feature Request] Reader View?

### ISSUE THREAD

**Issue by winteriscariot** [duckduckgo/iOS#884]
ive been using DDG for quite a while and really enjoy the browser. however both Safari and Firefox have a reader view which strips clutter from text articles to make a more pleasant reading experience (and giving an all black background for OLED screens). 

are there any plans to add such a feature to this browser?

**Comment by samsymons** [comment]
Thanks @winteriscariot, this is one of our biggest requests both internally and externally. We're tracking this closely and will ping you here if this feature is added to the app. Thanks again!
