### ISSUE TITLE
Endless periodic page refreshing without user action

### ISSUE THREAD

**Issue by matthme** [duckduckgo/iOS#892]
Since version 7.63.4.0 pages are sometimes endlessly refreshed without user action (i.e. once every few seconds the page is refresehd). This make reading a page absolutely impossible. It is not page specific but can happen on any page (it has also happened on a duckduckgo search result page once) so it is quite certainly a browser issue. There is however no clear pattern that I could identify regarding when it happens exactly. Usually after restarting the app it resolves but may appear again soon after on another page.

The phone I'm using is an Iphone 6s with iOS 13.6.1.

**Comment by brindy** [comment]
Thanks for letting us know. We are about to push out a release with a temporary fix imminently. A more comprehensive fix will come next week. Thanks for your patience!
