### ISSUE TITLE
Import/Export Bookmarks [Feature Request]

### ISSUE THREAD

**Issue by DirtyP4nts** [duckduckgo/iOS#896]
It would be great, if we could Import and Export our bookmarks. You implemented something like this in the Android Version.

[Android Feature Request](https://github.com/duckduckgo/Android/pull/1211) 

Maybe it would be possible to use the iCloud Drive to Export it there and import it in the same way. 

I would love to switch completely to your Browser but to move all my bookmarks would be such a pain.

**Comment by fruityperson** [comment]
Please add this feature. Export to TXT file will be enough

**Comment by brindy** [comment]
Hi - sorry for not replying sooner.  Just wanted to let you know we're definitely thinking/talking about it.

**Comment by Ph1thak** [comment]
Yes, this feature would be undoubtedly incredibly useful

**Comment by brindy** [comment]
Quick update here - we’re working on some improvements in this area.  Import/Export won’t be part of that, but it will lay the foundation for us to do that shortly afterwards.   Thanks for your patience! :)

**Comment by fewerjunk** [comment]
For the record:

https://github.com/duckduckgo/Android/issues/209

Now do IOS.  

"Patiently" waiting.

**Comment by samsymons** [comment]
Good news! This feature is nearing the end of development and is planned to ship in a release soon.

I'll update here once this has gone live.

**Comment by samsymons** [comment]
This is now available in version 7.67.0. Thanks everyone for the feedback! 🙂

![Bookmark Import Export](https://user-images.githubusercontent.com/183774/165109021-9bc248b0-d829-4f54-8e4a-67c6621bb221.jpeg)
