### ISSUE TITLE
Set DuckDuckGo as Safari Default

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/iOS#9]
I think we should do this up front on setup. I think we can look at how the keyboards do it (as they have super complicated setup requirements).

I think this is the highest priority.

**Comment by nilnilnil** [comment]
I also noticed last night that you can ask Siri to open Safari Settings. Perhaps we could experiment with those instructions too.

We'll likely need to have a way in the application to create a way to test these methods.

**Comment by subsymbolic** [comment]
The Siri option could work well, it's the fastest way to get to that safari setting that I know of. We could experiment with that (and a few other options) in a start-up tutorial when the user first installs the app. There are some A/B testing frameworks that could help us do that without the need to redeploy. I'll wrap up the today extension and get started on this tomorrow. We can flesh out some of the details during our call.

**Comment by subsymbolic** [comment]
The recent onboarding work has covered this.
