### ISSUE TITLE
History API is ignored if a page is opened in a new tab (target "_blank")

### ISSUE THREAD

**Issue by SimonBackx** [duckduckgo/iOS#901]
## Environment
App version: 7.63.7.0
Device model: iPhone 12 pro
iOS version: 14.6

## Steps to reproduce the bug

- Start with a simple website (the initial website) that opens a different website (the opened website) in a new tab when clicking on a link:
```html
<a href="https://example.com" target="_blank">Open in new tab</a>
```
- On the opened website, use the History API's pushState method (e.g. when clicking on a button) to navigate to a new page
```js
history.pushState({ currentPage: "page1" }, "Page 1")
```
- Press the back button in the browser to go to the previous page

## Expected behavior

It should go back to the first page of the opened website.

## Actual behavior

It goes back to the initial website and skips over the first page (or more intermediate pages) on the opened website.

## Example

I've made a small repository with example code and hosted it so you can try it yourself without having to write any code.

- Open the following URL (= the initial website) in DuckDuckGo's browser for iOS:
`https://simonbackx.github.io/push-state-example/open-in-tab.html`
- Click on the link `Open in new tab`
- Hit one or more buttons `Home`, `Page1`, or `Page2`
- Go back using the browser buttons. You'll see that any intermediary pages are skipped

Now compare this with the normal behavior:
- Open the URL of the opened website by entering it directly in DuckDuckGo's browser for iOS, instead of opening it in a new tab using the initial website:
`https://simonbackx.github.io/push-state-example/`
- Hit one or more buttons `Home`, `Page1`, or `Page2`
- Go back using the browser buttons. You'll see that everything works as expected

You can check the source at https://github.com/SimonBackx/push-state-example

**Comment by brindy** [comment]
Hi @SimonBackx - thanks for submitting this and sorry for not replying sooner.  We determine back/forward using the signals we get from WKWebView.   

I'm not sure there's much we can do about this, unless you have any ideas? It might better to create a bug for this in the WebKit issue tracker. https://webkit.org/reporting-bugs/

**Comment by SimonBackx** [comment]
As far as I know, WKWebView doesn't have any support for target _blank out of the box, so the current behaviour is probably custom. I'll look into it and if you are open for it, open a PR with a fix.

**Comment by brindy** [comment]
Yep, check these lines for starters:

* https://github.com/duckduckgo/iOS/blob/develop/DuckDuckGo/TabViewController.swift#L1268

And:
* https://github.com/duckduckgo/iOS/blob/develop/DuckDuckGo/TabViewController.swift#L1181

But essentially we just open a new tab with a WebView and let it carry on from there.

if you can work out what’s going, a PR would be welcome, Thanks!

**Comment by brindy** [comment]
Any thoughts @SimonBackx ?

**Comment by SimonBackx** [comment]
Hey @brindy,

I didn't manage to setup the right provisioning profiles to sign the app for development. Probably because DuckDuckGo is using a protected entitlement (e.g. com.apple.developer.web-browser) for the browser which I can't add to my App ID's at the moment. Am I right that I need to request permission to use this entitlement by emailing default-browser-requests@apple.com? Automatic provisioning profiles aren't working either. Do you have some steps to set this up?

**Comment by brindy** [comment]
@SimonBackx that's the right email but you won't get the entitlement without having an actual browser app on the App Store already - you sort of have to be proven already before you can get it.  Basically they don't want like gaming (or more malicious) apps being able to handle links and things like that so they are quite judicious about who they give it to.

Obvious thing to do is remove that entitlement, but I appreciate that's a little awkward.

@samsymons do you have any thoughts about this given you just merged a config related PR :)

**Comment by SimonBackx** [comment]
Sorry for the delay! I was on vacation and didn't have time to pick this issue up afterwards. I'll try to pick this issue back up the coming days 😊
