### ISSUE TITLE
ActionMessageView width overflow

### ISSUE THREAD

**Issue by Bunn** [duckduckgo/iOS#907]
The `ActionMessageView` used to display favorite and bookmark notification doesn't take smaller devices (like iPod touch and iPhone SE) window width into consideration.

Here's how it looks on an iPod touch:
<img src="https://user-images.githubusercontent.com/782316/123405165-74258900-d5a1-11eb-9a80-98a348a8feef.png" width="300">

When compared with a larger device, like the iPhone 8 we can see that the previous behavior is not expected, since it's missing margins and the rounded corners.
<img src="https://user-images.githubusercontent.com/782316/123405477-c8306d80-d5a1-11eb-97c1-db55b23555da.png" width="300">

Extra info:
**App version:** 7.63.8
**Device model:** iPhone SE or iPod Touch
**iOS version:** Tested on iOS 14, but it probably happens on others as well
**Steps to reproduce the bug**
- Tap the 3 dots at the bottom right corner
- Choose Favorite this page

**Expected behavior**
"Toast" message view appears with rounded corners and respecting margins

**Actual behavior**
"Toast" message view appears overflowing the device's width frame without any margin.

The same issue happens when removing the favorite or bookmarking a webpage.

**Comment by brindy** [comment]
Thanks for this, I'm testing it now.
