### ISSUE TITLE
Height calculation error when displaying onboarding messages

### ISSUE THREAD

**Issue by Bunn** [duckduckgo/iOS#910]
When the app displays the `subsequent` HomeScreenMessage on iPod touch or iPhone SE the label height is not correctly calculated.

Steps to reproduce:
- On an iPhone SE or iPod touch
- Open the app for the first time
- See first onboarding message
- Open a website
- Open a new tab
- See the `subsequent` onboarding message
- You can see that the last line overflows the box frame

![Screen Shot 2021-06-16 at 17 59 17](https://user-images.githubusercontent.com/782316/123558903-cb3d8080-d790-11eb-95e4-2cec9722c70a.png)

**Comment by brindy** [comment]
Thanks again for your contributions - I'll hopefully review it soon!

**Comment by brindy** [comment]
This has been merged.  Thanks for this!
