### ISSUE TITLE
Feature Request: See Recently Viewed Links

### ISSUE THREAD

**Issue by elielamora** [duckduckgo/iOS#914]
When browsing, it is often useful to preview recently visited sites for a given tab. It is a common features on other browsers, that I and other users are familiar and accustomed to.

For instance Safari:
<img width="476" alt="Screen Shot 2021-06-28 at 8 27 40 PM" src="https://user-images.githubusercontent.com/22871225/123854710-0ce33e00-d8ed-11eb-987b-4000b9621fbd.jpeg">

<img width="476" alt="Screen Shot 2021-06-28 at 8 27 40 PM" src="https://user-images.githubusercontent.com/22871225/123719387-685eee80-d84f-11eb-8f03-764478b77815.png">

The way I envision the feature working is:
* Long pressing on the back button opens the preview
* Clicking on a link to navigates to the link selected, updating the history stack
* Clicking on the background would dismiss the menu.

It should be simple to implement given that the history is accessible from webview namely the property [.backForwardList](https://developer.apple.com/documentation/webkit/wkwebview/1414977-backforwardlist). Also a lot of the legwork for displaying a menu is complete with BrowsingMenu.

Lastly regarding privacy, the tab history is already part of WKWebView and is already being stored. This simply allows the user to take advantage of the information already present. Once the tab is obliterated the recently visited stack is gone too.

Did not see any previous issues with a similar proposal.

**Comment by brindy** [comment]
Hi,

Thanks for your request. Unfortunately it’s not as simple as it might seem. You can see a previous discussion and attempt here:  #764 

The key point is that that the browser can be booted out of memory by iOS and we don’t have any way to store or restore the tab state so lose those back and forward details.

There is actually a private API for that but we obviously can’t use that.  See: https://github.com/WebKit/WebKit/blob/main/Source/WebKit/UIProcess/API/Cocoa/WKWebViewPrivate.h#L185

Other browsers like Firefox, Brave, Chrome have different work arounds for this but none are particularly palatable. 

Additionally we haven’t had that much demand for it, so it’s not been a priority, but I’ll certainly share this with the rest of the team.

Hope that helps.

**Comment by elielamora** [comment]
Thanks for the reference to the similar issue previously filed ([#764](https://github.com/duckduckgo/iOS/issues/764)).

I was envisioning the feature slightly differently from the previous proposal. In fact, I was thinking something similar to what was mentioned in the [last comment on the previous thread](https://github.com/duckduckgo/iOS/issues/764#issuecomment-732494662). Namely, adding a custom component as mentioned in the previous thread to keep the look and feel consistent with the BrowsingMenu. 

Also, I don't think that displaying the entire history needs to be displayed and it doesn't need to be restored. Showing what is in memory is fine. When/if session save/restore is implemented it will 'just work'.

Looking back at discussion for the previous issue, it seems the conclusion is that this feature has been roadmapped and is pending an internal design and review. If this isn't an opportunity for external contribution (which I'd be interested in) I think we can go ahead and close this issue. Looking forward for it seeing it in the wild.

**Comment by brindy** [comment]
Let me check with the rest of the team to see if they'd be comfortable with this as a contribution and to see if I can get some design for it.
