### ISSUE TITLE
Adding new tab from tab manager is jittery

### ISSUE THREAD

**Issue by romanrudyy** [duckduckgo/iOS#915]
The experience is somewhat jittery and could have a bit more polish. Here's what could be fixed:

1. Keyboard shows up before we transition from tabs manager to tab view, should be synced
2. When user hits add tab, tab cell added to the list should be blank with white background. Currently it has stuff with logo etc, and since transition begins in split second afterwards this is jittery
3. Logo animation is jittery. Especially when there is more than one screen of tabs in the manager. Logo appears from the bottom at the same time when keyboard appears. 

I have fixed these points, please see the attached videos. I'd also emphasise the jitter is better visible on an actual device and is kind of irritating. I can post a pull request if you folks agree with this. 

I would love to use DuckDuckGo browser but Safari is so much more polished and iOS 15 version is even further ahead, hence trying to help.

https://user-images.githubusercontent.com/68649232/123971580-dc6dd380-d9c2-11eb-9c9d-bc5345c99e13.mov

https://user-images.githubusercontent.com/68649232/123971609-e0015a80-d9c2-11eb-868c-a229b7181441.mov

https://user-images.githubusercontent.com/68649232/123971616-e1328780-d9c2-11eb-95d6-3edc300fdb4b.mov

https://user-images.githubusercontent.com/68649232/123971619-e263b480-d9c2-11eb-8eef-10e9238e0c66.mov

**Comment by brindy** [comment]
Hi - thanks for this, we're tracking it internally at https://app.asana.com/0/392891325557410/1200541656968208

They seem like a decent improvement, so let me check with the rest of the team to make sure they're comfortable taking this as a contribution.

**Comment by brindy** [comment]
Hi, yes, we'd welcome a PR for this.  Thanks in advance!
