### ISSUE TITLE
Link To App Store

### ISSUE THREAD

**Issue by dodekeract** [duckduckgo/iOS#94]
Would be nice if you could place a link to the App Store in the Repo description. Currently it just says "DuckDuckGo iOS Application". There is a "link" setting so you can show a link next to the description.

I'd send a PR, but it's unfortunately not possible to PR this change.

**Comment by subsymbolic** [comment]
Good idea. We're haven't released yet so I'll leave this open until we do as a reminder.

**Comment by xyclos** [comment]
It has been released now, correct? So, this should be updated to: https://itunes.apple.com/us/app/duckduckgo-privacy-browser/id663592361?mt=8

**Comment by brindy** [comment]
Done! Thanks folks!

**Comment by mayassuarez172** [comment]
Good Idea's Currently it just says "DuckDuckGo iOS Application". There is a "link" setting so you can show a link next to the description for more:
[https://github.com/mayassuarez172](https://github.com/mayassuarez172)
[https://github.com/mayassuarez172/blue-kitchen-cabinets](https://github.com/mayassuarez172/blue-kitchen-cabinets)
[https://mayassuarez172.github.io/blue-kitchen-cabinets](https://mayassuarez172.github.io/blue-kitchen-cabinets)

**Comment by janicetyler** [comment]
where the link is bro ? Currently it just says "DuckDuckGo iOS Application". There is a "link" setting so you can show a link next to the description.
[https://github.com/janicetyler](https://github.com/janicetyler)
[https://github.com/janicetyler/wood-kitchen-cabinets](https://github.com/janicetyler/wood-kitchen-cabinets)
[https://janicetyler.github.io/wood-kitchen-cabinets](https://janicetyler.github.io/wood-kitchen-cabinets/)

**Comment by lucialam172** [comment]
Currently it just says "DuckDuckGo iOS Application". There is a "link" setting so you can show a link next to the description. 
[https://github.com/lucialam172/dark-kitchen-cabinets](https://github.com/lucialam172/dark-kitchen-cabinets)
[https://github.com/lucialam172](https://github.com/lucialam172)
[https://lucialam172.github.io/dark-kitchen-cabinets](https://lucialam172.github.io/dark-kitchen-cabinets)
