### ISSUE TITLE
On iPad when closing a tab with address bar input in focus, the input gets carried over to previous tab's address bar

### ISSUE THREAD

**Issue by romanrudyy** [duckduckgo/iOS#943]
- App version: 7.64.2
- Device model: 2020 iPad Pro 11"
- iOS version: iOS 15b4
- Steps to reproduce the bug: 
  - Open tab 1, load a website
  - Tap the "+", open tab 2
  - Load a website in tab 2
  - Tap the address bar of tab 2
  - Close tab 2
- Expected behavior:  I get tab 1, address bar loses focus and has tab 1 url, keyboard is dismissed
- Actual behavior:  I get tab 2, address bar retains focus, has tab 2 url, keyboard is present. 

Please see the video demo:

https://user-images.githubusercontent.com/68649232/127742277-acb94ae4-935b-4ed4-8f49-056416d284e7.MP4

This behavior is also incorrect if tab 2 is a blank tab, but since it's blank it carries over the empty string to previous tab's address bar:

https://user-images.githubusercontent.com/68649232/127742300-c8076b64-dded-446a-a489-2cdf3c3514f2.MP4

Please let me know if you'd like me to do a PR and fix this.

**Comment by samsymons** [comment]
@romanrudyy Great spotting, we'd very much welcome a PR for this if you're up for it! If not, I have capacity to fix this bug on Friday. 🙂 

I'll assign this issue to myself for now, but if you open a PR for this by Friday morning then I'll review that and get it into the next release.

**Comment by romanrudyy** [comment]
hey @samsymons, I won't be able make it for Friday as I'm stacked on work, but I could give it a go on Sunday, if that sounds good 🙂

**Comment by samsymons** [comment]
@romanrudyy No problem at all, that would be fantastic - thanks so much!
