### ISSUE TITLE
The scroll insmooth problem of BrowserChromeManager.swift

### ISSUE THREAD

**Issue by unknown0521** [duckduckgo/iOS#945]
Hi, I have noticed that there is a scroll insmooth issue on the DuckDuckGo iOS App main screen, and I found the problem may inside your "BrowserChromeManager.swift" file. I have tried to improve it, the following video is the comparison:

https://www.youtube.com/watch?v=UTSwgAahmpI&ab_channel=FoodieFox

I really like this app and I just wish it can be better and better,
thank you for reading : )

Best Regards,
Frank Chen

**Comment by samsymons** [comment]
Hey @unknown0521!

This looks like a big improvement. 👏 Are you able to open your changes as a PR so I can share them with the team?

Thanks, and thanks so much for the kind words. 🙂

**Comment by unknown0521** [comment]
Hi @samsymons, 

I've tried to open a PR but it seems I don't have permission,
but I've sent related files to your HR two weeks ago when I once applied for your iOS developer position, I also fixed minor constraints issues in the "Settings.storyboard". I think Diana should have forwarded those files to the team already? if you can't find the files, I'm willing to mail them again. 

Although I can't have the chance to challenge the assignment test, try to improve the DuckDuckGo app is still an exciting thing for a faithful user.

Thanks so much for the kind words : )

![duckduckgo](https://user-images.githubusercontent.com/35766783/128573457-96e90372-dc79-4b2f-8d07-374543917df3.jpg)

**Comment by samsymons** [comment]
@unknown0521 The permission issue is interesting, do you have your own fork of the repo? If not, you can create one with the Fork button in the upper right and then push your changes to a branch there, which will let you open it as a PR. 🙂

If possible I'd love to get those as a PR as it's easier to track and review the changes on our end, and it also lets the changes go through our Bitrise CI process.

Thanks!

**Comment by samsymons** [comment]
Hey @unknown0521 – thanks again for opening this issue, I'll close this for now but if you do find time to open your fixes for this issue as a PR we'd be happy to take a look.

Thanks!

**Comment by Tommas2037** [comment]
954
