### ISSUE TITLE
Save passwords entered on webpages via ddg-browser

### ISSUE THREAD

**Issue by droid-user** [duckduckgo/iOS#953]
It is already possible to auto-fill passwords already stored in a password manager or the ios-vault. 

Compared to safari, DDG seems to lack the possbility to save new credentials into the vault entered within DDG. At least whenever I try, there is no prompt to save credentials after I hit "enter" on a login page. Credentials have to be added manually or via SAFARI.

If it is possible to hand over the credentials, it would be valuable to add this to DDG to make it THE standalone browser.

All the best, 

Fred

--------
Tested on: iPhone 12 mini, iOS 14.7.1

**Comment by brindy** [comment]
Hi Fred,

Thanks for your feedback and we definitely agree.  iOS doesn’t support this “out of the box” but we are planning to support it in the future.

I’m going to close this out because it’s already on our development timeline.

Thanks again!
