### ISSUE TITLE
Disable video autoplay

### ISSUE THREAD

**Issue by msmasters624** [duckduckgo/iOS#954]
People are getting bombarded with auto play videos, it is taking an excessive amount of bank width. Google has blocked this option, can we get this option for duckduckgo?

**Comment by samsymons** [comment]
Thanks for reporting this @msmasters624, we've had a couple folks ask for this; I've bumped the internal task that tracks this request.

I can't promise anything, but I'd like to solve this in the near future by offering a few autoplay options. If this ends up in a release, I'll ping you here to let you know – for now, closing this issue as it's tracked internally.

**Comment by intra-au** [comment]
@msmasters624  there's extension you can use to disable autoplay "Disable HTML5 Autoplay" if that helps :)
