### ISSUE TITLE
Why does window.alert() not work?

### ISSUE THREAD

**Issue by campbell-m** [duckduckgo/iOS#963]
Why does window.alert() not work in DuckDuckGo on iOS?   As in the following code

~~~html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <script>
    window.alert("hello");
    </script>
  </head>
  <body>
    <p>Test</p>
  </body>
</html>
~~~

**Comment by samsymons** [comment]
Hey @campbell-m! 

Thanks for reporting this, this is something that's on our roadmap. It's lower priority at the moment so I can't promise a timeframe for it being fixed, but I've added your request to the task internally.

Thanks again!
