### ISSUE TITLE
Fingerprinting tracking prevention

### ISSUE THREAD

**Issue by intra-au** [duckduckgo/iOS#970]
DuckDuckGo iOS version is susceptible to fingerprinting tracking. A number of unique features allow to create an unique fingerprint and track this device:
1. Non standard "User Agent"
2. Modified color depth - 24 bit instead of Safari standard 32 bit

Additionally some things below can be randomized to reduce effectiveness of fingerprint tracking:
1. Hash of canvas fingerprint
2. Hash of WEBGL fingerprint
3. Audiocontext fingerprint

Using DuckDuckGo I score at least 17,69 bits of identifying information making my browser an unique device among 212K tested in past 45 days. For comparison Safari Private mode on the same iPhone provides only 16.69 bits of identifying information while Brave provides only 15 bits reducing uniqueness to 1 in 35K browsers. 

Please see more details at: coveryourtracks.eff.org

**Comment by brindy** [comment]
Hello, thanks for opening this.  I'm going to share it internally with our privacy team.  We'll be tracking it internally here https://app.asana.com/0/392891325557410/1201029961025274 (private link)

Thanks again.

**Comment by brindy** [comment]
Hi @intra-au - just a quick update here. I passed to the privacy team and all these things are already on their radar.  Thanks again!
